### ISSUE TITLE
Graceful treatment and error reporting of unsupported MIME types for file uploads

### ISSUE THREAD

**Issue by scherr-stripe** [stripe/stripe-dotnet#1000]
https://github.com/stripe/stripe-dotnet/blob/4f79ed6ea8923fb2b593a298481bcd115efa12e8/src/Stripe.net/Infrastructure/Requestor.cs#L208

The above attempts to detect the MIME type by looking the file extension of `filename` using

https://github.com/stripe/stripe-dotnet/blob/4f79ed6ea8923fb2b593a298481bcd115efa12e8/src/Stripe.net/Infrastructure/MimeTypes.cs#L7-L23

When a user tries to upload an unsupported file this will return `null` which in turn ends up in a thrown  [`ArgumentException`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/MediaTypeHeaderValue.cs#L256) during `MediaTypeHeaderValue` construction.

I suggest the extension either be checked ahead of time or at the spot to, instead of returning `null`, yield a specific exception type and message. 

Secondly, I think it would be a good idea to perform MIME type detection on the file content instead of the filename where possible, for instance relying on `FindMimeFromData`. However, I am too unfamiliar with C# to provide a more informed suggestion here.

**Comment by xt0rted** [comment]
I was looking into `FindMimeFromData` for working with uploaded files and the result of what I found is that this method comes from `Urlmon.dll` which is only available on Windows with IE installed. So p/invoke aside this won't be available cross platform.

A 32 & 64 bit friendly example (uses `IntPtr` instead of `Int32`) can be found [here](https://stackoverflow.com/a/2826884/39605) for reference on how to use it.

**Comment by ob-stripe** [comment]
The underlying issue was fixed by #1054 and released in v11.8.2.
