### ISSUE TITLE
Change destination amount on pre auth charge

### ISSUE THREAD

**Issue by crono009** [stripe/stripe-dotnet#1017]
I'm currently implementing the two step payment flow and I'm wondering if there is a way to change the destination amount of the uncaptured charge. 

StripeChargeService.Capture() has a parameter for changing the captureAmount and applicationfee, but I can't seem to find a way to change the destination amount even though the stripe documents say you should be able to.  I was wondering if Stripe.net has this feature.

Also, does anyone know how to release a pre-auth charge if we no longer need it? I know if we don't capture it within 7 days it will release the funds, but I would like to do it earlier out of courtesy for the customer.

Thanks in advanced!

**Comment by remi-stripe** [comment]
@crono009 The `Capture` [method](https://github.com/stripe/stripe-dotnet/blob/f005b1b52ca42df408eaea4ccdd41b84820c3e24/src/Stripe.net/Services/Charges/StripeChargeService.cs#L57) does not support this just yet.

I think we would need to move `Capture` to using something like `StripeChargeCaptureOptions` instead of direct parameters in the method.

If you're up for submitting a PR, that would be awesome! If not, we'll do our best to get to it in the coming weeks.
