### ISSUE TITLE
Feature Request: Add support for auto-pagination

### ISSUE THREAD

**Issue by twilly86** [stripe/stripe-dotnet#1038]
Is there an easy way to List out all customers or subscriptions?  Right now I am having to write this code which handles the pagination.  

![image](https://user-images.githubusercontent.com/3496838/31680905-f5f3ed40-b332-11e7-81bc-305a31c8fa9b.png)

**Comment by anelder-stripe** [comment]
Ahoy!

So by default, if you just paginate through Subscriptions/Customers without any arguments, you'll get all of them.  Limit is capped at 100 objects per request, because otherwise your request would likely timeout.  Additionally, in your code example above, your date filter is going to try and retrieve all subscriptions from the beginning of time to a year into the future, so that `Created` argument isn't actually doing anything.

The code below is an example of pagination to get all objects ever (in this case Charges):

https://gist.github.com/anelder-stripe/94b1e736bd3ac31eedc65e257747f0ed

Is this feature request a request for auto-pagination (like what we support in the Python library)?  It's a bit unclear to me what you're looking for here.

**Comment by twilly86** [comment]
sorry for the lack of clarification.  This request would be for the ability to auto-paginate, basically wrap the code in your Gist snippet into a single function called subscriptionService.Scan() which will scan every single record.

**Comment by ob-stripe** [comment]
Not sure when we'll be able to get to this, but tagging it as `future` for now.

**Comment by a-patel** [comment]
any update on this?

**Comment by ob-stripe** [comment]
This feature was added in 22.0.0. You can find more information in the migration guide: https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v22#auto-pagination. We will update the documentation on Stripe's site soon.
