### ISSUE TITLE
StripePlanListOption doesn't exist

### ISSUE THREAD

**Issue by muhihsan** [stripe/stripe-dotnet#1046]
I found that in the https://stripe.com/docs/api/dotnet#list_plans, it says if I want to get list of plans for certain options, I need to pass `StripePlanListOptions` to `new StripePlanService().List(...)` method. But the `List(..)` method itself has the following signature 

`public virtual StripeList<StripePlan> List(StripeListOptions listOptions = null, StripeRequestOptions requestOptions = null);`

where it accepts `StripeListOptions` not `StripePlanListOptions`. Also I couldn't find `StripePlanListOptions` in the latest Stripe.net library. 

From there, I believe the documentation should refer to `StripeListOptions` instead of `StripePlanListOptions`.

I am using Stripe.net v11.6.1.

![image](https://user-images.githubusercontent.com/18164621/32034799-9cc4dc7c-ba60-11e7-85f8-d09316cc09a1.png)

**Comment by ob-stripe** [comment]
Hi @muhihsan, thanks for reporting this! We will fix this promptly.

**Comment by geedsen** [comment]
Any update on this?

**Comment by ob-stripe** [comment]
Hi @geedsen. This is actually part of a larger issue described in #974, as there are other services that would need to be updated to have their own dedicated `ListOptions` classes.

Since this is going to be a breaking change, we'll want to do all of them at once to avoid releasing multiple major versions. I don't have any ETA to share, but it's definitely on our roadmap.

**Comment by ob-stripe** [comment]
Fixed in v12.0.0.
