### ISSUE TITLE
Issue with Login Link

### ISSUE THREAD

**Issue by btackney** [stripe/stripe-dotnet#1081]
I'm having trouble with stripe.net login link use with my connected Express accounts. The below code never throws an error but stops the view from ever loading, it just sits their acting like its trying to load. The account id matches a connected test account id my correct keys are in place. Thanks.

`var loginLinkService = new StripeLoginLinkService();`
`StripeLoginLink loginLink = loginLinkService.Create(account.Id);`
`ViewBag.link = loginLink.Url;`

Stripe.net Version 11.10.0 (updated yesterday hoping to fix issue)
.Net Version 4.5.2
Visual Studio 2017

**Comment by ob-stripe** [comment]
Hi @btackney. There might be an issue with your test account. In any case, I don't think it's an issue with the stripe-dotnet client library -- if the request does not return anything, it's likely an issue on the API's end.

Can you reach out to support at https://support.stripe.com/email to ask about this issue? Make sure to include the ID of your test Express account, and if you can, timestamps for the login link creation requests you sent. We will be able to dig into your account's logs and help you figure out what's happening exactly.

I'm closing the issue for now as this is likely no a client-side issue, but we will reopen if that turns out to be the case.

**Comment by mattlokk** [comment]
I am having the same issue.  I believe this is a bug in the SDK.  The thread just dies upon calling LoginLinkService.Create()  and no exception is thrown.

**Comment by remi-stripe** [comment]
@mattlokk Please write in to support with more details and they can help investigate!
