### ISSUE TITLE
Use custom BaseUrl

### ISSUE THREAD

**Issue by jamesmckenzie** [stripe/stripe-dotnet#1102]
## Feature Request

The library should allow the user to provide a custom url for testing purposes. 

**Use case** - testing an application that uses this client library in conjunction with a mock server (e.g. stripe-mock)

**Comment by remi-stripe** [comment]
@jamesmckenzie It's definitely something we'd like to support in the library in the future, especially to support stripe-mock as it would make iterating on the library a lot faster. I've tagged it as "future" for now as it's not something we'd be able to tackle immediately but we will look into it!

**Comment by remi-stripe** [comment]
cc @ob-stripe what do you think?

**Comment by ob-stripe** [comment]
Great feature request! It's definitely something that the library needs :)

I think the best place for this would likely be the [`StripeConfiguration`](https://github.com/stripe/stripe-dotnet/blob/c5cb2432117c2d83a097fd241a5eb7899854d5f6/src/Stripe.net/Infrastructure/Public/StripeConfiguration.cs) class. In order to be consistent with our other libraries, we'd want 3 methods:
- `SetApiBase` to override the API base URL (defaults to `https://api.stripe.com`)
- `SetUploadsBase` to override the file upload base URL (defaults to `https://uploads.stripe.com`)
- `SetConnectBase` to override the Connect/OAuth base URL (defaults to `https://connect.stripe.com`)

Happy to review a PR if you're up for it @jamesmckenzie :)

**Comment by jamesmckenzie** [comment]
thanks for the info, will put something together.

**Comment by jamesmckenzie** [comment]
PR in for the above (sorry for the delay, had some computer issues!)

**Comment by ob-stripe** [comment]
Released in 13.4.0, which should appear in NuGet shortly. Thanks again for your contribution @jamesmckenzie, much appreciated!
