### ISSUE TITLE
an odd error, A member with the name 'product' already exists on 'Stripe.StripePlanCreateOptions'. 

### ISSUE THREAD

**Issue by farshadjahanmanesh** [stripe/stripe-dotnet#1109]
"Stripe.net" version="13.0.1" targetFramework="net461" , windows 10

this a simple error, there is two "product" in StripePlanCreateOptions class, can you change it?
## A member with the name 'product' already exists on 'Stripe.StripePlanCreateOptions'. Use the JsonPropertyAttribute to specify another name.

**Comment by remi-stripe** [comment]
@farshadjahanmanesh I've tried locally and can't seem to reproduce that error. Are you sure you are on the latest version (13.0.1)? Here's the code I'm using:

```
            var planOptions = new StripePlanCreateOptions() {
              Product = new StripePlanProductCreateOptions() {
                Name = "Titanium performance"
              },
              Amount = 5000,
              Currency =  "usd",
              Interval = "month",
            };

            var planService = new StripePlanService();
            StripePlan plan = planService.Create(planOptions);
```

**Comment by farshadjahanmanesh** [comment]
![image](https://user-images.githubusercontent.com/13612410/36510725-5567f078-1779-11e8-8e14-748618c3bb78.png)
yes, i call  it from PostMan ... 
we have a post api like this
![image](https://user-images.githubusercontent.com/13612410/36510817-9f4ec694-1779-11e8-8226-6de270211207.png)
and call it from our Frontend app... but it can not convert json to object
![image](https://user-images.githubusercontent.com/13612410/36510857-bd951446-1779-11e8-8dc4-0e61a7b9e676.png)

**Comment by remi-stripe** [comment]
Can you clarify what you mean by "but it can not convert json to object"? What is making the conversion exactly? I'm not following what the issue is and in which context it happens.

**Comment by farshadjahanmanesh** [comment]
![image](https://user-images.githubusercontent.com/13612410/36511050-8f0bda6e-177a-11e8-93e6-976765296eaa.png)
here, .net  convert the json to object automatically but i get null as "planOptions" every time when i call this method

**Comment by remi-stripe** [comment]
But what in your code creates `planOptions`? Are you sure you're not incorrectly setting `Product` twice by mistake, for example passing `Product` and `ProductId`?

**Comment by remi-stripe** [comment]
I'm still a bit lost. I've never used any of the tools you mention so I don't grasp what turns your JSON into a StripePlanProductCreateOptions exactly. But I do think there's a bug in your code where you set both ProductId and Product and so it then fails. You need to double check the code and ensure that you only set `Product` and not `ProductId` in your example.

**Comment by farshadjahanmanesh** [comment]
i think there is something wrong with the library, because this is a very straightforward asp.net, we send a json to  an api, and .net,  automatically convert that json to The corresponding object, but here there is something wrong,

**Comment by farshadjahanmanesh** [comment]
if  i am the only one that have this issue, u=you can close this, i am create my own helper object and use them 
thank you for your responsiveness

**Comment by remi-stripe** [comment]
I have not heard about anything similar yet but those changes are fairly recent so it's likely that not everyone has moved onto it just yet.

I will close for now but will reopen if we hear more reports!

**Comment by ob-stripe** [comment]
I'm not sure I grasp what you're trying to do exactly either, but I think I can shed some light on the issue.

Newtonsoft.Json is used in a somewhat idiosyncratic way in Stripe.net: we use the `JsonProperty` attribute to tag fields in request parameters, however request parameters are never actually encoded to JSON. Rather, Stripe's API expects request parameters to be URL-encoded (`application/x-www-form-urlencoded`, not `application/json`).

Because some request parameters can be polymorphic (e.g. `product` when creating a plan can either be a string with an existing product's ID or a map with the new product's attributes), in some cases we have multiple fields tagged with the same value in `JsonProperty`. This would cause an error if you try to actually do some JSON serialization/deserialization on those classes, which is what you're trying to do here if I understand correctly.

I don't have full context on why the library was designed this way, but if I had to take a guess I'd say it's because the library does use Newtonsoft.Json "normally" to decode the JSON objects returned by Stripe's API, and doing this allows to have some symmetry between request parameters and Stripe entities.

**Comment by farshadjahanmanesh** [comment]
thank you, yes i am try some json serialization/deserialization on those classes, and yes you are right its because the application/json, now i have create some helper classes for this . thank you again
