### ISSUE TITLE
Newtonsoft.Json v11 on Stripe v13.3.0 (is it really necessary?)

### ISSUE THREAD

**Issue by MonDeveloper** [stripe/stripe-dotnet#1125]
Hi guys!

I'm integrating your sdk into my backend api, it works like a charm and it is one of the most and well documented piece of code here around.
Well done!

I'm just facing a noisy situation, my base libraries rely on Newtonsoft 10.x and my "base library team" told me they will take at least 1 or 2 months to release a version of that libraries compatible with 11.x because of 2 main reason (coding+testing & third party packages not yet compatible).

I think this is should be a not so rare scenario.

Unfortunately you have been so fast in update your mandatory dependency that it is impossible to me to stay update to your library (because you declared the 11 as minimium dep) and my other third party are still bounded with the 10.

I think many implementers are suffering my problem because the 10.x was out for a long time and the 11.x introduced some breaking changes so i think many third party libraries will take time to update...

Do you have any suggestion to stay on synch with your lib ?

**Comment by ob-stripe** [comment]
Hi @MonDeveloper! That's certainly an issue, and it sounds like we may have been too hasty in bumping the Newtonsoft.Json version number.

After reading a bit more about how [package versioning](https://docs.microsoft.com/en-us/nuget/reference/package-versioning) works, it appears that the version number specified in a `< PackageReference>` is the _minimum_ version number (unless some special notation is used). Since the stripe-dotnet library works fine with Newtonsoft.Json 9.0.1, we should be able to leave the version number with that value and users would still be able to use the library, even if they use version 10 or 11 of Newtonsoft.Json.

I'm going to revert the change. Thanks for the report and sorry for the trouble!

**Comment by MonDeveloper** [comment]
Firt of all, thanks guys, we at Crif appreciate a lot your prompt reply!

about the topic, you wrote:
> it appears that the version number specified in a < PackageReference> is the minimum version number (unless some special notation is used)

yes, the brand new `<PackageReference>` semantic let you specify not only the version you need but you can also put some constraint to specify which degree of flexibility your library will accept, for example you can declare the dotenet-stripe is dependend by Newtonsoft.Json with a minimum verions of 9.0.0 and a maximum version of 11, moreover the semantic let you declare if the boundaries are included or excluded so you can say that your library can accept any version of Newtonsoft until the next major (where some breacking changes are expected) and so on.


Again, thank you very much!
mM

**Comment by ob-stripe** [comment]
@MonDeveloper This is fixed in 13.3.1, which will appear on NuGet shortly. Thanks for your patience and sorry for the inconvenience!

**Comment by MonDeveloper** [comment]
No problem sir, we got it yesterday and it is under testing right now.

Thanks for your support.

Il Lun 5 Mar 2018, 21:56 Olivier Bellone <notifications@github.com> ha
scritto:

**Comment by iamcarbon** [comment]
Can we also considering bumping the Newtonsoft dependency back up to 11.0.2 to eliminate any transitive dependencies to .NETSTANDARD 1.x libraries?
