### ISSUE TITLE
Unexpected character encountered while parsing value: {. Path 'three_d_secure'

### ISSUE THREAD

**Issue by renjithr2081** [stripe/stripe-dotnet#1131]
Hello ,

I just now upgraded to Stripe.net 13.3.1.0 , and getting the  error
Unexpected character encountered while parsing value: {. Path 'three_d_secure', line 24, position 21.
We are in LIVE now so its affecting our customers.

**Comment by remi-stripe** [comment]
@renjithr2081 You should roll back to the previous version of stripe-dotnet that you had to avoid any issue in production. Then you can debug this locally in Test mode and investigate some of the changes and better understand what could cause this. Our support team should be able to help investigate this further as it could be due to specific settings set on your account. You can contact them here: https://support.stripe.com/email

**Comment by renjithr2081** [comment]
Hello , 

I am now testing in TEST environment.
I basically use the same code as the old version. 2.8

 var myCharge = new StripeChargeCreateOptions
            {
                Amount = aount,
                Currency = eventcurrency,
                Description = stripeDesc,
                SourceTokenOrExistingSourceId = tokenid
            };
 var stripeKey = ConfigurationManager.AppSettings["StripeKey"].ToString();
            var chargeService = new StripeChargeService(stripeKey);
stripeCharge = chargeService.Create(myCharge);

And the error happens in the last line Create

**Comment by remi-stripe** [comment]
@renjithr2081 A lot has changed in the library since your version, especially the API version. You should work with our support team to investigate the logs on your account and any custom settings you might have and they can then help you investigate. Github issues are not the right forum to discuss account specific problems with the library though.

You can reach out to them here: https://support.stripe.com/email

**Comment by renjithr2081** [comment]
I contacted Stripe and they told its not stripe error , since the charge is created sucessfully

**Comment by renjithr2081** [comment]
Any one can help me??

**Comment by ob-stripe** [comment]
@renjithr2081 Your Stripe account likely was onboarded for the old 3DS beta, which the Stripe.net library does not support. You need to ask Stripe support to disable the old 3DS beta feature on your account.

**Comment by renjithr2081** [comment]
I am using 3DS using Stripe.js , so you mean which is not supported now?

**Comment by ob-stripe** [comment]
The library does support 3DS using the sources API: https://stripe.com/docs/sources/three-d-secure.

As @remi-stripe said before, this is not a support channel. GitHub issues are specifically for bugs or feature requests with the library. You need to explain your issue to Stripe's support at https://support.stripe.com/email and they will be able to help you with this.

**Comment by renjithr2081** [comment]
I got the error , after upgrading the latest Stripe.net which means there is some bug.
And as I said before I already contacted Stripe , they said the charge is been registered when using the API , so there is no problem in Stripe side...
So please tell me whom should I contact when both parties tell its not their problem

**Comment by renjithr2081** [comment]
Very bad support from this team.. sorry to say..

**Comment by remi-stripe** [comment]
@renjithr2081 I know this can be frustrating but unfortunately this is not a bug with our library. The library is strongly typed and attached to a specific API version. This means that when your account has old custom settings it might not be supported by the latest version of the library.

We have no insights into your account when talking to you through github issues. This means that we can not confirm our assumptions, look at your logs and work with you on the right path moving forward.

The only solution here is to talk to our support team again. We (olivier and I) work for Stripe too and we can help the support team investigate and debug the issue with your account. But for that to happen, you need to talk to them again. Explain that you talked to us, linked this issue in your message and they can escalate internally and ping us so that we can help you.

**Comment by renjithr2081** [comment]
Now here is the reply from Stripe.....


Hi there Renjith,

Having a look over the post I see you've already received assistance.

When it comes to posting queries on Github you may find you get a quicker response than here- as we do have some time zone differences and there are developers world wide on Github. Github, as you saw from your interaction, is a great place to receive developer assistance- however it isn't a support portal. Unfortunately, I'm only here to provide the tools and use of Stripe. When it comes to your own development there's not a whole lot of assistance I can provide.

If you have any queries about using Stripe please let me know- I'd like to help.

Cheers,

Frankie

**Comment by remi-stripe** [comment]
@renjithr2081 Sorry for the confusing answer. I'll work with the support team so that the answer gets to us and we can help

**Comment by ninjaboy** [comment]
I am sorry to bother you guys but I need an advice here.
I have just installed Stripe and implementing integration for my company.
The latest installed version is 15. I can see that this discussion mentions that v12 didn't have this error.
Does it really mean that I should downgrade to v12 in order for this error to not appear?

**Comment by remi-stripe** [comment]
@ninjaboy A better solution would be to move to the official integration for 3DS as documented [here](https://stripe.com/docs/sources/three-d-secure) and contact our support team [here](https://support.stripe.com/email) to remove the setting on your account letting you use the old version of 3DS.
