### ISSUE TITLE
StripeChargeService.ApiKey not set from StripeConfiguration.SetApiKey

### ISSUE THREAD

**Issue by joshnoe** [stripe/stripe-dotnet#1155]
Using this code...
```
StripeConfiguration.SetApiKey(stripeApiKey);
var chargeService = new StripeChargeService();
```

chargeService.ApiKey is null.

I apologize if this is intentional and I just missed it in the docs. If so, it wasn't intuitive for me at least.

Stripe.Net version: 15.3.2
.NET version: 4.5
OS: Windows 10

**Comment by jaymedavis** [comment]
Since you aren't providing an api key (overload of the StripeChargeService constructor), the service doesn't know anything about an api key, yet. StripeConfiguration's api key is interrogated when the [requestor determines which key to use](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Infrastructure/Requestor.cs#L123). 

To make the library show the apikey you expected, the [StripeService](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/StripeService.cs) (every service inherits from here) could be modified to read the global state in the event the service state wasn't supplied by the user. I just elected not to couple them, for better or worse.

Hope this helps!

**Comment by jaymedavis** [comment]
If you don’t set the key on the service state, or call SetApiKey to set the global state, .net 4.5 tries to read “StripeApiKey” from your config as a last resort.
