### ISSUE TITLE
Updating sub qty causes during trial causes proration adjustment charge.

### ISSUE THREAD

**Issue by mscrivo** [stripe/stripe-dotnet#1166]
We have a subscription plan that has a trial set of 30 days.  This had been working fine with Stripe.NET v12.1 and below.   We'd create the subscription, set the qty to 1 and the trial period was properly obeyed.  Ever since upgrading to 13+, the call to set the Qty to 1 has been causing a proration adjustment that has been effectively charging our customers for the trial period.  The only difference I can see between 12 and 13 is the format of the API request:

12:

`POST to /v1/subscriptions/sub_xyz`
with body:
```
{
  "quantity": "1"
}
```
results in "Subscription has changed in the event log"

13+:
`POST to /v1/subscriptions/sub_xyz`
with body:
```
{
  "items": {
    "0": {
      "id": "si_xyz",
      "quantity": "1"
    }
  }
}
```
results in "A proration adjustment has been created for $ was create for <customer>"

Am I using the new version of the library incorrectly?  Even if I was, I don't see why updating the qty from 0 to 1 immediately after creating the subscription, would nullify the trial period set for the plan type.

**Comment by remi-stripe** [comment]
@mscrivo Looking into that subscription, you have created it without any trial period. Because of this, the subscription was already active which is why there was a proration item created.

My guess is that your code is not sending the `TrialEnd` parameter. Since you now use the `Items` approach then trial periods on the plan are ignored by default. You have to explicitly pass `trial_end` when you create the subscription or `trial_from_plan: true` instead.

I'd recommend reaching out to our support team if you have follow up questions as I don't think it's specific to the code in the library itself.

**Comment by mscrivo** [comment]
@remi-stripe Ok that's interesting, I don't recall reading that in the breaking changes. It really should be noted that the trial period set on the plan would be ignored, as that's not at all clear, nor user friendly.  The previous behaviour was much more intuitive IMO. 

Thanks for the quick assistance though, I appreciate it.

**Comment by mscrivo** [comment]
One other reason the new approach is bad is that we now have to keep details about which plans have trials and which don't in our code.  Previously, I could have common code that created/updated subscriptions and rely on Stripe to handle if it was a trial or not.  Beautifully elegant, now, it seems there is extra work to do in the code to support plans with and without trials.
