### ISSUE TITLE
Unexpected character encountered while parsing value: {. Path 'three_d_secure'

### ISSUE THREAD

**Issue by renjithr2081** [stripe/stripe-dotnet#1196]
[error.txt](https://github.com/stripe/stripe-dotnet/files/2065758/error.txt)
This is in continuation with the issue , 
https://github.com/stripe/stripe-dotnet/issues/861

Any updates on the issue??
As the date is nearby to upgrade the API I am giving another try..

The scenario is the same as explained by sortit-craig in the orginal case [861](https://github.com/stripe/stripe-dotnet/issues/861)
The Charge is created but the response object something is wrong.

error.txt

Attaching the complete error I get after calling , chargeService.Create(myCharge);

Please help

**Comment by remi-stripe** [comment]
@renjithr2081 There's no bug in the library here. The issue is that you have a really old gate on your account which changes the way the API behaves for you. You need to talk to our support team directly instead here: https://support.stripe.com/email

**Comment by renjithr2081** [comment]
I am doing in the TEST which point to the latest API
<img width="987" alt="screen shot 2018-06-04 at 14 51 41" src="https://user-images.githubusercontent.com/11088227/40918528-d4e0be88-6806-11e8-92c6-e351ea32676f.png">

Please check.
I am trying both at Stripe support to help resolve it.
June 13th is the last date for us to upgrade and we already have clients in our platform 

Appreciate if you can guide us

**Comment by remi-stripe** [comment]
@renjithr2081 This is unrelated to the API version. Your Stripe account has an old gate. That's an internal Stripe setting that we add to specific accounts that can give them access to features in beta that have not been announced publicly. Your account has a really old one for 3DS, from before we released Sources. You likely need that gate removed and should talk to our support team directly, not here, so that they can help.
