### ISSUE TITLE
Product field on Plan is always null

### ISSUE THREAD

**Issue by SimonChris** [stripe/stripe-dotnet#1204]
In the new API, the Plan object now has a Product field and a ProductId field. When I fetch a plan, the ProductId field is set correctly, but the Product field is always null.

This happens regardless of whether I fetch a single plan or a list of plans. There does not seem to be anything in the request options for this.

Is there a way to retrieve plans along with their products? I assume the field is there for a reason?

**Comment by remi-stripe** [comment]
@SimonChris That is expected behavior. The `Product` parameter is just a hash to create a product inline for you while creating the plan. It does not return the product back to you in that case. If you want the Product to be expanded when you fetch a plan, you need to use the [Expand] feature which lets you get the Product back when you retrieve or create a plan. You can see it in the code here: https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/StripePlan.cs#L44
