### ISSUE TITLE
Enhancement: Please add the decline code to the charge object.

### ISSUE THREAD

**Issue by zerobounce** [stripe/stripe-dotnet#1247]
Can you please add the decline code to the charge object. The current charge object has the FailureCode which maps to "code" and FailureMessage that maps to "message" but the FailureDeclineCode is missing and should map to "decline_code" 

{
  "error": {
    "charge": "ch_1CvniGCVPrIw8vG8LQs21231",
    "code": "card_declined",
    "decline_code": "do_not_honor",
    "doc_url": "https://stripe.com/docs/error-codes/card-declined",
    "message": "Your card was declined.",
    "type": "card_error"
  }
}

**Comment by remi-stripe** [comment]
@zerobounce The [Charge object](https://stripe.com/docs/api#charge_object) does not have a `decline_code` property which is why it's not defined there. The example you gave above is not a Charge object but instead an error response which happens when a charge creation fails for example.

In this case, if the error is caused by a bank decline, the `code` will be `card_declined` and the `decline_code` will be set. This property is already defined on the StripeError class [here](https://github.com/stripe/stripe-dotnet/blob/5b6a010515e94cd72f6bef4659350922f023d2cf/src/Stripe.net/Entities/StripeError.cs#L17-L18)
