### ISSUE TITLE
Enhancement: Please add CRUD methods to StripeService class with override those in successor classes

### ISSUE THREAD

**Issue by evorios** [stripe/stripe-dotnet#1248]
I want to write my custom wrapper around this methods because it all have standart call `var result = service.Get(Id);`

**Comment by remi-stripe** [comment]
@evorios Would you be able to provide a bit more details around the functionality we're missing and what you want us to add to the library? Even some pseudo-code example would be useful!

**Comment by ob-stripe** [comment]
If I understand correctly, @evorios would like to have CRUD methods (`Create`, `Get`, etc.) be defined in the `StripeService` / `StripeBasicService` classes.

We cannot do this because not all services implement all CRUD methods (in fact, most services don't). However, in #1269 we've added interfaces that can be used to know _which_ CRUD methods are implemented by a service.

This will be released in the next major version (cf. #1293) -- no ETA yet but it shouldn't be too long.

Closing this, but feel free to reply if you think interfaces won't work for your usecase.
