### ISSUE TITLE
No code comment or docs in lib 

### ISSUE THREAD

**Issue by LeoJHarris** [stripe/stripe-dotnet#1261]
We just starting using stripe and noticed theres nearly no documentation, just as a suggestion or enhancement it would be really helpful if you at least provided some code comments within the library more specifically the .net lib even if only on top of methods etc.

**Comment by remi-stripe** [comment]
@LeoJHarris A lot of the library has documentation aroundproperties and parameters today. For example you can look at the `StripeCharge` class [here](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/StripeCharge.cs) or the class `StripeChargeCreateOptions` used to create a charge [here](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Charges/StripeChargeCreateOptions.cs).

Not all the library is documented though, especially the methods as they seem self explanatory since they are mostly `Create`, `Get`, `Delete`, etc. 

We also highly recommend relying on our API reference documentation which you can find here: https://stripe.com/docs/api/dotnet#intro

**Comment by xt0rted** [comment]
@remi-stripe I was just looking at the nuget package and there's no `Stripe.xml` alongside `Stripe.dll`. Any IntelliSense comments in the code won't be available when consuming the package then.

This should be easily fixed by adding `<GenerateDocumentationFile>true</GenerateDocumentationFile>` to the project file.

**Comment by remi-stripe** [comment]
@xt0rted Thanks for the extra info! We'll look into whether that's something we can support in the future!

**Comment by comtsamsmith** [comment]
I second this.  Above is a reply to "really" good info which gives a 404 error.  The objects are like the Stripe documentation but not the same...  Its OK creating something clever but shame its hard to understand how to use it.

**Comment by remi-stripe** [comment]
@comtsamsmith We have been actively adding comments to the majority of classes over time and all new classes have comments built in by default now. Would you be able to provide a bit more details about what you think is missing in the library and what has been confusing you?

**Comment by remi-stripe** [comment]
As of today, the library is fully generated from the openapi spec. It means that all properties and parameters are fully documented similarly to what appears in the API Reference which should resolve this long standing issue for everyone!
