### ISSUE TITLE
StripeSubscriptionService Cancel() missing cancel_at_period_end option 

### ISSUE THREAD

**Issue by PaulDMendoza** [stripe/stripe-dotnet#1263]
Nuget Stripe.net version: 19.1.0

https://stripe.com/docs/api/curl#cancel_subscription

The StripeSubscriptionService Cancel() method is missing some way of passing the **cancel_at_period_end** argument. It used to be there in version 17 but is missing now in version 19.1.

**Comment by remi-stripe** [comment]
@PaulDMendoza This is expected behaviour. This parameter was removed on API version [2018-08-23](https://stripe.com/docs/upgrades#2018-08-23). You are now expected to use the Update Subscription API instead.

This was changed in the latest major version and is also covered in the [Changelog](https://github.com/stripe/stripe-dotnet/blob/master/CHANGELOG.md#1900---2018-08-27). I recommend reading that file whenever you switch to a new major revision.
