### ISSUE TITLE
StripeFileUploadService : Uploading file fails due to MimeType

### ISSUE THREAD

**Issue by sumit4palz** [stripe/stripe-dotnet#1278]
While trying to upload file using code below I am getting a Stripe Exception with the message:

> We don't currently support that file type. Try uploading a file with one of the following mimetypes: application/pdf, image/jpeg, image/png. 

I believe this issue has something to do with FileStream, because when I create a file stream for file which exists on a disk upload **works fine.**   Here is the sample code which fails with StripeException.

>        [HttpPost]
>         [Route("upload")]
>         public async Task PostFile(IFormFile uploadedFile)
>         {
>             try
>             {
>                 StripeConfiguration.SetApiKey("validapikey");
>                 
>                 var filePath = Path.GetTempFileName();
> 
>                 using (var fileStream = new FileStream(filePath, FileMode.Open))
>                 {
>                     uploadedFile.CopyTo(fileStream);
>                     
>                     var service = new StripeFileUploadService();
>                     StripeFileUpload upload = service.Create(uploadedFile.FileName, 
>                         fileStream, StripeFilePurpose.DisputeEvidence);
>                 }
>             }
>             catch (Exception e)
>             {
>                 Console.WriteLine(e);
>                 throw;
>             }
>         }

**Stripe.net - v15.3.0
Asp.net Core : 2.0.3**

   ```
at Stripe.Infrastructure.Requestor.ExecuteRequest(HttpRequestMessage requestMessage)
   at Stripe.Infrastructure.Requestor.PostFile(String url, String fileName, Stream fileStream, String purpose, StripeRequestOptions requestOptions)
   at Stripe.StripeFileUploadService.Create(String fileName, Stream fileStream, String purpose, StripeRequestOptions requestOptions)
   at Api.Controllers.DisputesController.<PostFile>d__5.MoveNext() in D:\TSASource\Payments\Src\Payments.Api\Controllers\DisputesController.cs:line 75
```

**Comment by ob-stripe** [comment]
Hi @sumit4palz. This error message is returned by the API whenever it cannot verify that the contents of the uploaded file match one of the expected file types for the file's purpose.

I'm not sure the .NET library is involved in this issue -- although it does send a `Content-Type` header with a MIME type depending on the filename, the API actually ignores the header and checks the MIME type itself by looking at the file's contents.

Would you mind reaching out to support at https://support.stripe.com/email with all the information above, as well as approximate times at which you attempted the failed queries? This way, we will be able to check our internal logs and have a better idea of what happened.

Closing for now, but I will reopen if this turns out to be an issue with the library.
