### ISSUE TITLE
BalanceTransactionId is not available while using Sofort

### ISSUE THREAD

**Issue by renjithr2081** [stripe/stripe-dotnet#1299]
Hello , 

I integrated sofort yesterday using sources.
And found that once the transaction is complete BalanceTransactionId is not getting populated in the Charge object.

balance_transaction in the Charge JSON Response

Is it because the Transaction status is in Pending?
What is the solution

**Comment by ob-stripe** [comment]
Hi @renjithr2081. This doesn't sound like an issue with the stripe-dotnet library. You should reach out to Stripe's support at https://support.stripe.com/email to ask your question. Make sure to include the ID of the charge so that our support staff can look at your logs and confirm whether this is expected behavior or not.
