### ISSUE TITLE
Unable to concatenate List<StripeSubscription>

### ISSUE THREAD

**Issue by devWaleed** [stripe/stripe-dotnet#1314]
I have been trying to concatenate lists of type 'StripeSubscription' but unable to make it work for pagination.

```
var subscriptions = new List<StripeSubscription>();

var temp_subscriptions = subscriptionService.List(options);

subscriptions.Concat(temp_subscriptions.Data);

while (temp_subscriptions.HasMore)
{

    options.StartingAfter = temp_subscriptions.Data.Last().Id;

    temp_subscriptions = subscriptionService.List(options);

    subscriptions.Concat(temp_subscriptions.Data);

}
```

**Comment by ob-stripe** [comment]
Hey @devWaleed, you might have figured this out already since you closed the issue, but I think the problem with your code lies in this line:

```c#
subscriptions.Concat(temp_subscriptions.Data);
```

[`Concat`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.concat?view=netframework-4.7.2#System_Linq_Enumerable_Concat__1_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEnumerable___0__) doesn't modify its caller, it returns a new list. You probably want [`AddRange`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.addrange?view=netframework-4.7.2) instead.
