### ISSUE TITLE
Extend Token expiry?

### ISSUE THREAD

**Issue by LeoJHarris** [stripe/stripe-dotnet#1324]
Hi there I believe I saw your token has an expiry of a couple of minutes.  Would it ever be possible to see the ability to actually set the token max lifetime? We have an app where the payment might not occur with in the 10 mins even on the same day! So need the token to live beyond the 10 minutes currently. Is there a way to do this now? If might this be able to be added into the road map?

**Comment by ob-stripe** [comment]
Hey @LeoJHarris. Card and bank account tokens don't have a set expiry date, but they're meant to be short-lived and used ~immediately after creation.

If you want to save a token to bill the card / bank account at a later time, what you should do instead is use the token to [create a customer object](https://stripe.com/docs/api#create_customer) (or [add a card](https://stripe.com/docs/api#create_card) / [bank account](https://stripe.com/docs/api#customer_create_bank_account) to an existing customer object). You can then save the customer's ID as well as the card's / bank account's ID in your database, and use them to create charges anytime you need.

Since this isn't an issue with the stripe-dotnet library, I'm going to close the issue. If you have more questions, please follow up with Stripe's support at https://support.stripe.com/email.
