### ISSUE TITLE
Can't provide 'now' or 'unchanged' to Upcoming Invoice API

### ISSUE THREAD

**Issue by metanoic** [stripe/stripe-dotnet#1336]
So, the `StripeUpcomingInvoiceOptions` object has `SubscriptionBillingCycleAnchor` as a `DateTime?`, which doesn't afford the ability to specify 'now'.  This is in contrast to `StripeSubscriptionUpdateOptions`'s `bool` properties of `BillingCycleAnchorNow` and `BillingCycleAnchorUnchanged`.

I think `StripeUpcomingInvoiceOptions` should implement this like `StripeSubscriptionUpdateOptions` does.

If the maintainers are willing to accept a PR, I'm fine with doing the work though I may need assistance with updating the tests.

**Comment by remi-stripe** [comment]
@metanoic Thank you for the report. Usually we would happily take a PR but we are actively working on the next major release of stripe-dotnet which contains a large number of changes. You can see the work in https://github.com/stripe/stripe-dotnet/pull/1293. Because of this, it might be tricky for you to make the changes on that branch, and rebasing on an updated master would be fairly painful (though not impossible).

I'm going to make the changes on that branch which we're hoping to release by early next week if that works for you!

**Comment by remi-stripe** [comment]
@metanoic I just realized that this was already done in that PR and you can see the new code [here](https://github.com/stripe/stripe-dotnet/blob/9f0526a37958ea9f8ecfd1f8bc2514c82e36f8be/src/Stripe.net/Services/Invoices/UpcomingInvoiceOptions.cs#L32-L65). This should be released soon!

**Comment by metanoic** [comment]
@remi-stripe Excellent; ya'll rock!

**Comment by ob-stripe** [comment]
Fixed in 20.0.0.
