### ISSUE TITLE
Expand product property when listing plans

### ISSUE THREAD

**Issue by Ranjit-S** [stripe/stripe-dotnet#1351]
Using Windows 10, .NET Core 2.1 and Stripe.net 20.1.0.

After upgrading to Stripe.net 20.1.0, an exception is thrown when retrieving plans and setting `PlanService.ExpandProduct` field to true.

The error message is: "This property cannot be expanded (product). You may want to try expanding 'data.product' instead".

Using the following code:
```c#
var service = new PlanService();
service.ExpandProduct = true;
service.ListAsync(planListOptions);
```

A workaround to this issue is by appending "data.product" to `PlanListOptions.Expand` list and leaving the `PlanService.ExpandProduct` property set to false.

**Comment by ob-stripe** [comment]
Hey @Ranjit-S, thanks for the report. This is a regression that was introduced in version 20.0.0. We'll work on a fix and release an updated version soon.

**Comment by remi-stripe** [comment]
@Ranjit-S Since you are using this property I wanted to ask what you thought if we removed it in a future version of the library.

For context, we shipped the ability to expand multiple levels of properties a while ago by using `AddExpand`. The idea is that you can list Balance Transactions and expand the invoice on a charge that is a source of the balance transaction by doing `AddExpand("data.source.charge")`. With this existing, it makes the `ExpandXXX` properties a bit confusing as they only work for one level.

For now we decided to keep those because we think it's valuable to know what is expandable at the first level but I'm thinking it would have removed some of the confusion.

**Comment by ob-stripe** [comment]
Fixed in 20.2.0.

**Comment by Ranjit-S** [comment]
> @Ranjit-S Since you are using this property I wanted to ask what you thought if we removed it in a future version of the library.
> 
> For context, we shipped the ability to expand multiple levels of properties a while ago by using `AddExpand`. The idea is that you can list Balance Transactions and expand the invoice on a charge that is a source of the balance transaction by doing `AddExpand("data.source.charge")`. With this existing, it makes the `ExpandXXX` properties a bit confusing as they only work for one level.
> 
> For now we decided to keep those because we think it's valuable to know what is expandable at the first level but I'm thinking it would have removed some of the confusion.

@remi-stripe I agree, having the single level expand property is unnecessary now I know of `AddExpand` function and it's flexibility. It would be helpful to have a simple explanation of the function in the readme doc.

**Comment by remi-stripe** [comment]
@Ranjit-S Thanks a lot for the feedback, that's exactly what I was looking for!
