### ISSUE TITLE
SourceTokenOrExistingSourceId is missing for StripeChargeCreateOptions()

### ISSUE THREAD

**Issue by justlearntutors** [stripe/stripe-dotnet#1360]
var chargeOptions = new Stripe.ChargeCreateOptions()
                    {
                        Amount = PriceIntPayment,
                        Currency = "usd",
                        Description = "Lesson",
                        SourceTokenOrExistingSourceId = token// obtained with Stripe.js
                    };

Error
'ChargeCreateOptions' does not contain a definition for 'SourceTokenOrExistingSourceId'

**Comment by remi-stripe** [comment]
@justlearntutors The 20.0.0 library introduced a lot of breaking changes and one of those was to renamed `SourceTokenOrExistingSourceId` to `SourceId`. The long name was confusing a lot of users because it tried to document the API instead of matching what developers saw in tutorials or the API ref so we renamed it everywhere.

As long as you pass the token id `tok_12345` in that property the charge will work as expected.
