### ISSUE TITLE
v20 DefaultSource changed to interface.  Any advice on migrating?

### ISSUE THREAD

**Issue by aim12340** [stripe/stripe-dotnet#1369]
Hi,

It's not clear how to solve this breaking change.  My v19 code creates a customer with:
Stripe.Customer stripeCustomer = new Stripe.CustomerService().Create(customerOptions);

Now DefaultSource properties error, e.g. stripeCustomer.DefaultSource.Card has on Card property because DefaultSource is now a IPaymentSource.

I guess I need to cast to the correct interface.  What is the recommended way to do that?

And for similar problems, where can we find out which interface we need to cast to?

Thanks for an awesome library!

Eamonn

**Comment by ob-stripe** [comment]
Hi @aim12340. There are different ways to handle this, but my recommendation would be to use [pattern matching](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching):

```c#
switch (stripeCustomer.DefaultSource)
{
    case BankAccount bankAccount:
        // do something with bankAccount
        break;
    case Card card:
        // do something with card
        break;
    case Source source:
        // do something with source
        break;
}
```

Of course, if you already know the type beforehand (e.g. because you only accept cards on your site, and you know that all your customers are created with card tokens, not bank account tokens or sources), you can simply cast directly:
```c#
var card = (Card)stripeCustomer.DefaultSource;
// do something with card
```

Does this help?

**Comment by ob-stripe** [comment]
Hi @aim12340.

> Maybe you could add .Card etc properties to IPaymentSource? It would give you back the Intellisense discoverabiilty.

I'm very much in favor of anything that helps library users, but I'm not sure we could implement this specific suggestion, since the `Card` / `BankAccount` / etc. layer no longer exists. Classes that implement the `IPaymentSource` interface may have completely different properties -- the interface doesn't actually define any specific contract, it simply signifies that classes that implement it can be used as payment sources.

We could expand the XML comment on the interface to explicitly list the classes that do implement this interface. Do you think that would help?

> I really like the automatic conversion to DateTime, good time saver, I actually removed code form my project!

Can you clarify what you mean by this exactly? We did remove the `JsonConverter` attributes on `DateTime` properties in v20 because we added a globally applied converter, but this is causing issues with users who are manually deserializing resources with `JsonConvert.DeserializeObject`, so we're going to revert that change in an upcoming version (cf. #1368). Would that affect you?

**Comment by aim12340** [comment]
Hi,

I understand they aren't polymorphic that way.  I was thinking IPaymentSource.Card could return a Stripe.Card object/interface or null if its the wrong type.  Adding some info the the comments might be enough. 

I'm using dates in event webhooks, converting from unix time to DateTime myself, so I've been able to replace this:
`DateTime periodEnd = ParseUnixTimestamp((string)invoice.lines.data[0].period.end);`
with this:
`DateTime periodEnd = (DateTime)invoice.Lines.Data[0].Period.End;`

That's a good change.  I don't think changes to deserializing will affect me.

**Comment by ob-stripe** [comment]
Hi @aim12340, thanks for the feedback!

The next release of stripe-dotnet (21.2.0) will include extended documentation on the three interfaces `IBalanceTransactionSource`, `IExternalAccount` and `IPaymentSource` so that library users know which types to test for when receiving one of these. Hopefully that helps clear things up.

Thanks for the additional details regarding `DateTime` -- I'm glad you find this change useful :)
