### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by jmawebtech** [stripe/stripe-dotnet#1380]
Hi,

If I have more than 100 records, how do I implement paging?
```c#
List<Invoice> invoices = new List<Invoice>();
InvoiceService service = new InvoiceService(UserName);
service.ExpandCustomer = true;
service.ExpandCharge = true;
service.ExpandSubscription = true;
invoices.AddRange(service.List(new InvoiceListOptions()
{
    Limit = 100,
    DateRange = new DateRangeOptions()
    {
        GreaterThanOrEqual = order.GetDueDate().AddDays(-1),
        LessThanOrEqual = order.GetDueDate().AddDays(1)

    }
}).ToList());
```

**Comment by remi-stripe** [comment]
When you paginate, the idea is that you keep calling the List API method but always fetching the next page. For this, the API uses cursor-based pagination.

This means that when you fetch a given page, you tell Stripe to start after the last element in the previous page. So if you get 100 charges first and the last one in the page is ch_1234, you fetch the next page and pass `StartingAfter: "ch_1234"` so that we know to start at the next one. 

You can stop your loop when the response has `HasMore: false` which means you reached the end of the list.
