### ISSUE TITLE
Add CouponId to InvoiceCreateOptions, InvoiceUpdateOptions & InvoiceFinalizeOptions

### ISSUE THREAD

**Issue by jamrocktech** [stripe/stripe-dotnet#1403]
Version: **Stripe.net.21.4.0**
Fellow DevHeads & Colleagues,

I have searched the Issues list to see if a similar request has been submitted and did not find a match.

I am requesting the addition of the CouponId attribute to the aforementioned options for Invoices which when when presented, would apply and create the Discount object (if the Coupon is valid at the time).

To be sure, this is for one-off Invoices as this is handled via subscription driven Invoices.

I observed this functionality in the dashboard when creating just such an Invoice  (one-off).

My work-around is currently conducted as follows

-  Allow the selection of a forever coupon during editing
-  Apply it during Update/Finalize to the Invoice as an InvoiceItem
-  Place the details on the Coupon in the Metadata of the Invoice for reference when editing or reviewing
-  Keep a separate track of the redemption of Coupons used to combine the official with the unofficial to give an accurate redemption count.

This is definitely not for the feint of heart and to be sure, I lose the uptick on the redemption count for said Coupon.

I think it would be beneficial for Users to be able to see the "official" tracking of the redemption from Stripe versus other methods such as I described.

Thanks for the consideration.

**Comment by remi-stripe** [comment]
@jamrocktech There is no way to apply a Coupon to a given invoice via the API today. The coupon used on a invoice must be added to the corresponding Subscription or Customer instead. The Invoice resource "inherits" the coupon from those.  If you are creating one-off invoices via the API, you would set the Coupon on the customer.

Since this is not a question about the library itself and more about the Billing product, I'd recommend reaching out to our support team if you have any follow up questions. You can contact them here: https://support.stripe.com/email

**Comment by remi-stripe** [comment]
@jamrocktech The Invoice has a `discount` property showing the coupon that was applied to it yes.
