### ISSUE TITLE
Support for ConnectionToken 

### ISSUE THREAD

**Issue by jbcullis** [stripe/stripe-dotnet#1514]
FEATURE REQUEST

Can we get support for the ConnectionToken as per stripe terminal documentation.
https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/Terminal/ConnectionTokens/ConnectionToken.cs

**Comment by ob-stripe** [comment]
Hi @jbcullis. Can you clarify what you mean? Support for Terminal resources was added in Stripe.net [21.2.0](https://github.com/stripe/stripe-dotnet/blob/master/CHANGELOG.md#2120---2018-11-12). Is there a particular feature that's missing?

**Comment by jbcullis** [comment]
Maybe I just can't see it, but I'm looking for a correlating service and object for https://api.stripe.com/v1/terminal/connection_tokens

**Comment by ob-stripe** [comment]
I think [`Stripe.Terminal.ConnectionTokenService`](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Terminal/ConnectionTokens/ConnectionTokenService.cs) is what you're looking for.

Most of Stripe's new features such as Terminal are grouped under a specific sub-namespace, e.g. `Stripe.Terminal`. Maybe that's why you didn't find the service? I've just noticed that the code sample at https://stripe.com/docs/api/terminal/connection_tokens/create doesn't mention that you you need to have a `using Stripe.Terminal;` statement for it to work. I'll let our docs team know!

**Comment by jbcullis** [comment]
Ahh perfect, I didn't see the Stripe.Terminal object there, I expected it at the root. Sorry for wasting your time.

**Comment by ob-stripe** [comment]
No worries at all!
