### ISSUE TITLE
Constants changed

### ISSUE THREAD

**Issue by theleprechaun33** [stripe/stripe-dotnet#1569]
Why were the constants such as Events changed to just be strings? The comment says they were changed to readonly strings, but they are just static string. I ask because they are now unusable in a switch statement. Please advise.

**Comment by ob-stripe** [comment]
Hi @theleprechaun33. You can see the discussion in #1423 for more context, but the tl;dr is that you'll need to replace your `switch/case` statements with a series of `if/else if` (cf. https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v22#constants-are-now-static-read-only-properties).

Closing since this is a known limitation, but feel free to reply.
