### ISSUE TITLE
checkout.session.completed Event

### ISSUE THREAD

**Issue by JohnMcAvinue** [stripe/stripe-dotnet#1592]
Hi,

I'm upgrading my implementation to support Strong Customer Authentication. I have created the Checkout Session and it works fine with the user being redirected to the success URL after payment.

I'm now looking at performing the fulfilment automatically using a web hook as outlined here: https://stripe.com/docs/payments/checkout/fulfillment#webhooks

On this page, it says my web hook should be handling the event "checkout.session.completed".

I cannot see anything like this in Stripe.Events in Stripe.Net version 25.10.0 though.

What should I be using? Is there any documentation on how to do this? Everything in the Stripe API is PHP, Ruby, Node or Python which is frankly ridiculous as JAVA and .NET are enterprise level frameworks which are used by far more businesses than those.

Thanks

**Comment by ob-stripe** [comment]
Hi @JohnMcAvinue. The library was lacking a constant for the `checkout.session.completed` event type -- this will be fixed promptly.

More generally, you are correct that the documentation on Stripe's site is incomplete right now. I will raise this issue internally and we'll try to follow up before too long.

In the meantime, you can find the basic structure for an ASP.NET webhook controller here: https://stripe.com/docs/webhooks/signatures#verify-official-libraries.

In order to access the nested object in the event (e.g. in the case of a `checkout.session.completed` event, the `CheckoutSession` object), you'll need to cast `Data.Object` to the right type. You can use either pattern matching or rely on the event's `Type` attribute to cast to the correct type. You can find basic examples of both approaches here: https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v20#interfaces-for-polymorphic-resources.

**Comment by ob-stripe** [comment]
We just released version 25.12.0 of the library, which includes [`CheckoutSessionCompleted`](https://github.com/stripe/stripe-dotnet/blob/eadacdf3f9d119b59d97b7eea8f4194aa691c048/src/Stripe.net/Constants/Events.cs#L149-L152).

Closing the issue, but feel free to reply if you have questions or feedback.

**Comment by JohnMcAvinue** [comment]
Thanks very much for such an incredibly fast response - a new version within hours of my question, impressive!

I'm up and running now. Thanks once again

**Comment by ob-stripe** [comment]
@JohnMcAvinue You're welcome! We've also updated the docs on Stripe's site (https://stripe.com/docs/payments/checkout/fulfillment#webhooks) with basic examples of webhook handlers for .NET and Java.
