### ISSUE TITLE
PaymentIntent is not expandable when creating a subscription

### ISSUE THREAD

**Issue by nvoisin** [stripe/stripe-dotnet#1630]
Hi,
I'm currently following the billing tutorial [here](https://stripe.com/docs/billing/subscriptions/payment) and when creating a subscription using the CreateAsync method : `Subscription oSubscription = await _oSubscriptionService.CreateAsync(oOptions);` the subscription does not contain a `PaymentIntent ` in `oSubscription.LatestInvoice.PaymentIntent`. I have set the property `_oSubscriptionService.ExpandLatestInvoice = true;` but it stops there : I get the latest invoice without the PaymentIntent.  Currently the only solution I found was retrieving the PaymentIntent via the PaymentIntentService with the PaymentIntentId provided in the LatestInvoice.

Is there a way to get it directly as shown in the guide ? Am I missing something ?

Thanks,

**Comment by ob-stripe** [comment]
Hi @nvoisin. There are two different ways to expand properties using the Stripe.net library:
1. by setting `ExpandFoo = true` on the service instance used to make the request
2. by calling `.AddExpand("foo")` on the options instance passed to the method used to make the request

The problem with the first way is that it only lets you expand properties that exist directly on the resource managed by the service. E.g. in your case, you can expand `invoice` on the subscription, but you can't tell it to expand `payment_intent` in the invoice itself.

You can solve this issue with the second way:
```c#
var options = new SubscriptionCreateOptions
{
  // subscription creation parameters
};
options.AddExpand("latest_invoice.payment_intent");
var subscription = await subscriptionService.CreateAsync(createOptions);
var paymentIntent = subscription.LatestInvoice.PaymentIntent;
```

Hope this helps! Closing the issue since I don't think there's any action we need to take regarding the Stripe.net library. If you have followup questions, please reach out to Stripe's support using the form at https://support.stripe.com/email. Our support engineers will be happy to help you.

**Comment by nvoisin** [comment]
And how would I go about it with the subscriptionService get method, as it only supports RequestOptions that dont have a AddExpand method ?

Thanks

**Comment by remi-stripe** [comment]
@nvoisin This is not possible today unfortunately. You would have to retrieve the Invoice separately to expand its PaymentIntent. It's something we hope to fix in the future though.

**Comment by ob-stripe** [comment]
As of version 27.0.0, you can now request arbitrary expansions even in retrieve requests.

For example:
```c#
var subscriptionService = new SubscriptionService();
var options = new SubscriptionGetOptions();
options.AddExpand("latest_invoice.payment_intent");
var subscription = subscriptionService.Get("sub_123", options);
```
