### ISSUE TITLE
Feature: Get and Update the customer fields: "Send emails to" and "Send emails to CC"

### ISSUE THREAD

**Issue by andenis** [stripe/stripe-dotnet#1641]
Hi, I need Get and Update the customer fields: "Send emails to" and "Send emails to CC".  (In the Stripe dashboard works fine)
 
 I use the last .Net SDK Version (26.0.0) from Nuget packages. 
 
 These fields aren't in the Customer object. 
 {
   "invoicing": {
     "email_to": [
       "customer1@test.com"
     ],
     "email_cc": [
       "customer2@test.com"
     ]
   }
 }

Can you contemplate these fields in the next release?
Thanks.
Andres Denis

**Comment by remi-stripe** [comment]
@andenis Unfortunately, this feature is not available in the API today. It's only available in the Dashboard. That's why it's not in the library. We don't have short-term plans to make those fields available just yet though it might happen in the future. I'd recommend asking our support team for more details: https://support.stripe.com/contact

**Comment by przywartya** [comment]
Hi @remi-stripe ,any updates on adding this functionality to the API? Or maybe you have a workaround ready for calling the dashboard.stripe.com directly?

**Comment by remi-stripe** [comment]
@przywartya Same answer as on the ruby thread, no update for now and no short term plan to add this to the API at the moment
