### ISSUE TITLE
Question about payment method details

### ISSUE THREAD

**Issue by Andrewangeta** [stripe/stripe-dotnet#1663]
I'm writing a [StripeLibrary](https://github.com/vapor-community/StripeKit) and had a question about the payment details vs sources. 
Are the Stripe payment method details essentially the sources? Or since payment methods will replace sources at some point, should I start only relying on the docs for the Payment method details and leave the sources as they are?

**Comment by remi-stripe** [comment]
@Andrewangeta `PaymentMethod` is a new resource that was introduced to replace `Card`, `BankAccount` and `Source` objects and unify them all as a new abstraction.

To help with the migration, we have introduced the `payment_method_details` concept on the `Charge` object. This surfaces information specific to the payment method used for the Charge, whether it's a Card or a PaymentMethod, at the time of the Charge. This is a "snapshot" of that object and helps surface relevant information to Customers.

I would definitely recommend moving to reading from `charge.payment_method_details` as documented here: https://stripe.com/docs/payments/payment-intents/migration/reading-from-charges#read

Also, since you're building a third-party library based on our SDK, make sure to use the `AppInfo` approach as documented [here](https://github.com/stripe/stripe-dotnet#writing-a-plugin). This helps tag all those requests as coming from your library (and is easier to debug on both sides when issues happen!).

**Comment by Andrewangeta** [comment]
@remi-stripe Thanks! I'll follow that route then.
