### ISSUE TITLE
Plan Tiers won't allow null for UpTo

### ISSUE THREAD

**Issue by jrstuart42** [stripe/stripe-dotnet#1674]
when creating a plan with tiers i get an error "Stripe.StripeException : Missing required param: tiers[3][up_to]." i filled in the other necessary information for plan and the tiers look like the code below. UpTo is a nullable long. it should be able to take null as a value considering stripe allows null for it too.

```c#
Plan plan = new Plan()
{
    //other necessary info omitted
    Tiers = new List<PlanTier>()
    {
        new PlanTier()
        {
            UnitAmount = 7000,
            UpTo = 500
        },
        new PlanTier()
        {
            UnitAmount = 6000,
            UpTo = 1000
        },
        new PlanTier()
        {
            UnitAmount = 5000,
            UpTo = null
        }
    }
};
List<PlanTierOptions> planTierOptions = plan.Tiers.Select(pt => new PlanTierOptions()
{
    FlatAmount = pt.FlatAmount,
    UnitAmount = pt.UnitAmount,
    UpTo = pt.UpTo
}).ToList();
PlanCreateOptions createOptions = new PlanCreateOptions()
{
    Active = true,
    Amount = plan.Amount,
    Currency = plan.Currency,
    Id = plan.PlanID,
    Interval = plan.Interval,
    IntervalCount = plan.IntervalCount,
    Nickname = plan.Nickname,
    Product = plan.ProductID,
    Tiers = planTierOptions,
    TiersMode = plan.TiersMode,
    TrialPeriodDays = plan.TrialPeriodDays,
    UsageType = plan.UsageType
};
```

**Comment by ob-stripe** [comment]
@jrstuart42 `up_to` cannot be `null`, it must be either an integer or the `inf` special value: https://stripe.com/docs/billing/subscriptions/tiers.

You'd need to change your code like this:
```c#
Plan plan = new Plan
{
    Tiers = new List<PlanTier>
    {
        new PlanTier
        {
            UnitAmount = 7000,
            UpTo = 500,
        },
        new PlanTier
        {
            UnitAmount = 6000,
            UpTo = 1000,
        },
        new PlanTier
        {
            UnitAmount = 5000,
            UpTo = PlanTierUpTo.Inf,
        }
    }
};
```

Closing as I don't think this is a bug with the library, but feel free to reply.

**Comment by jrstuart42** [comment]
that didn't work. it gave the error "StripeException: Invalid positive integer"

**Comment by ob-stripe** [comment]
Ah sorry, I see the issue now. You're assigning values to a `Plan` instance, then creating the `List<PlanTierOptions>` instance from the `Plan` instance.

This has the side-effect of converting the `PlanTierUpTo.Inf` value from a `PlanTierUpTo` to a `long` (because `PlanTierUpTo` is an enum and so can be converted to int values). So in the `PlanTierOptions` instance, `UpTo` is `0` instead of `PlanTierUpTo.Inf`, which causes `0` to be send in the request, which in turn causes the API to fail the request with "Invalid positive integer".

It's a bit unorthodox to be creating any `StripeEntity` yourself in order to create request parameters. You can fix your code by creating the `List<PlanTierOptions>` directly:

```c#
PlanCreateOptions createOptions = new PlanCreateOptions()
{
    // other properties omitted for brevity
    Tiers = new new List<PlanTierOptions>
    {
        new PlanTierOptions
        {
            UnitAmount = 7000,
            UpTo = 500,
        },
        new PlanTierOptions
        {
            UnitAmount = 6000,
            UpTo = 1000,
        },
        new PlanTierOptions
        {
            UnitAmount = 5000,
            UpTo = PlanTierUpTo.Inf,
        }
    }
};
```
to avoid the lossy conversion from `PlanTier` to `PlanTierOptions`.

We'll see if there's something we can do to prevent this lossy conversion happening in the first place.

**Comment by jrstuart42** [comment]
@ob-stripe that worked. thank you!

**Comment by ob-stripe** [comment]
Glad I could help! I've also started working on a possible solution to prevent this (very confusing!) error from happening in the first place. It will likely be released in the next major version because it'd technically be a breaking change, but you can take a peek at #1675 if you're interested.
