### ISSUE TITLE
How are Webhooks configured? (be default)

### ISSUE THREAD

**Issue by Worthy7** [stripe/stripe-dotnet#1695]
So, what is the "latest" way to parse inputs?

Looking at the tests it doesn't seem obvious.

I see some Webhook config code, are we supposed to be somehow setting up the endpoints using the Stripe Service?
Or are we supposed to be making the endpoint ourselves, then passing it on somewhere?

A solid example on one of the doc pages would go a lot way, thanks.

**Comment by ob-stripe** [comment]
@Worthy7 Have you checked the examples on Stripe's site? https://stripe.com/docs/webhooks/setup and https://stripe.com/docs/webhooks/signatures include examples showing how to deserialize event objects using the latest version of the Stripe.net library.

**Comment by Worthy7** [comment]
No I totally did not see that, because the heading doesn't look like it has anything to do with how to receive a hook. "Receiving Webhook sample" would have been great lol.
In that case, what does the webhook tests do?
https://github.com/stripe/stripe-dotnet/blob/master/src/StripeTests/Services/WebhookEndpoints/WebhookEndpointServiceTest.cs

Thanks

**Comment by ob-stripe** [comment]
@Worthy7 [`WebhookEndpointService`](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/WebhookEndpoints/WebhookEndpointService.cs) is the service class for sending requests to [manage webhook endpoints](https://stripe.com/docs/api/webhook_endpoints) using the API. In many cases it's simpler to set up your webhook endpoints manually using [the dashboard](https://dashboard.stripe.com/webhooks) (since setting up the endpoints is typically a one-off operation that doesn't need to be automated).

When actually implementing the route in your integration, you want to use the helper methods in [`EventUtility`](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Events/EventUtility.cs) to deserialize the requests sent by Stripe into `Stripe.Event` instances, as shown in the links from my previous message.

We're aware the documentation around webhooks is a bit unclear / hard to find right now, and will improve it in the future.

Closing the issue, but feel free to reply!
