### ISSUE TITLE
Order creation fails if either a Coupon or OrderItem of discount type is present

### ISSUE THREAD

**Issue by HopesOblivion** [stripe/stripe-dotnet#1697]
I'm using stripe.net 27.9.0 (though this also happens in older versions).

Using the Orders API I'm trying to create an order either by using a stripe coupon, creating a discount line item or by providing an amount for the line item.

#### Using a coupon code

1. Create a coupon code in stripe, set its duration to once 
2. Set OrderCreateOptions.Coupon value to the newly created coupon id

Results: The order fails to create with the following JSON. Oddly enough if I look at the coupon details in the stripe dashboard, the coupon's redemption counter does increase each time.

`{
  "error": {
    "code": "order_creation_failed",
    "doc_url": "https://stripe.com/docs/error-codes/order-creation-failed",
    "message": "Order creation failed while contacting the provider.",
    "type": "card_error"
  }
}`

#### Using a "discount" line item

1. Include an OrderItemOptions.Type = "discount"
2. I tried including or omitting the quantity field, it makes no difference

`  new OrderItemOptions { Type = "discount", Amount = -599, Currency = "usd", Description = "Sweet six dollar discount" } `

Results: Order creation still fails with an identical response to the coupon case.

#### Changing the price of a line item
Since neither of the above work and the coupon system is pretty limited anyway (no way to create a coupon that only applies to some skus in an order for example) I figured why not roll my own and just change the line item's price?

Results: Changing the line item price doesn't do anything, the returned order object continues to use the default price for the sku. Why even bother having the field then? Seems a bit confusing.

So is there anyway to use coupons or discounts with the Orders API? I'm not sure if this is a bug in stripe-dotnet or the Stripe API in general. Looking at my logs in the dashboard all of the requests look identical to the examples in the documentation and the JSON appears to be formed correctly.

**Comment by remi-stripe** [comment]
@HopesOblivion Thanks for the report. I don't think this is a bug with stripe-dotnet and instead is a limitation of the API. Today, you can not add a negative line item or change a product price, this is not supported. 
I would recommend following up with our support team instead to explain your use-case and provide concrete examples of the failed request so that they can help you debug this: https://support.stripe.com/contact

**Comment by HopesOblivion** [comment]
> Today, you can not add a negative line item

If you attempt to add a "discount" line item that is not negative it will actually throw a message that indicates it must be negative.

**Comment by remi-stripe** [comment]
@HopesOblivion Yes but that message does not mean that exactly. You can not add a discount or negative item on order creation. You can add a coupon to the order but as far as I know that's the only thing that would work.

I'd recommend following up directly with our support team though as the issue is not with the library itself.
