### ISSUE TITLE
Broken API Architecture 

### ISSUE THREAD

**Issue by granthoff1107** [stripe/stripe-dotnet#1704]
Perhaps I'm missing something, but the API seems to be over typed, and I'm trying to figure out a simple way to update things.  This issue seems to be with the overall architecture of all the endpoints but maybe if I'm lucky Im missing something simple.

I've created a Stackoverflow issue here:
https://stackoverflow.com/questions/56980060/stripe-connect-api-update-paymentintent

Payment Intent service defines these method stubs:

    public PaymentIntent Get(string paymentIntentId, 
        PaymentIntentGetOptions options = null, RequestOptions requestOptions = null)
    public PaymentIntent Update(string paymentIntentId, 
        PaymentIntentUpdateOptions options, RequestOptions requestOptions = null);

I would like to update an entity...  So I call the Get, and then Change the Property I would like to change however there is no way to pass the payment intent to the Update, I need to map all of the properties with either an external dependency or manually.

    var paymentIntentService = new PaymentIntentService();
    var paymentIntent = paymentIntentService.Get(transaction.ExternalTransactionId);

    if (null != destinationStripeAccount)
    {
        paymentIntent.TransferData.DestinationId = destinationStripeAccount.AccountId;
    }
    
    //If this really requires an update options I should at least be able 
    // to pass the payment Intent to it
    paymentIntentService.Update(paymentIntent.Id, new PaymentIntentUpdateOptions(paymentIntent));

This seems like a hassle but for all of the API I need to map an object to pretty much a clone of this.   Why isn't there a simple way to update using the entity that was returned from the Get?

**Comment by ob-stripe** [comment]
Resource attributes and request parameters usually overlap, but they don't map 1:1 so we cannot use the resource model class by itself for request parameters.

Initializing the update options instance from the model instance also doesn't seem feasible. We would have to track which properties have been updated on the model since it was instantiated. We've actually done something similar in the past in some of our other client libraries (for less strictly typed languages like Ruby/Python/PHP) and have decided to move away from this approach as it caused a number of issues (for things like nested parameters, or parameters that share the same name as a resource field but have a different shape, etc.).

Ideally, the models returned by the library would be immutable (i.e. properties would not have setters), however some of our users like being able to manually instantiate model classes and set properties for testing purposes. The "right" way to use the library in production code is to set the request parameters directly in the request options instance, not by updating properties on the model instance.

Closing this since I don't think we're going to take any action here, but feel free to reply.

**Comment by granthoff1107** [comment]
Thanks for your quick response and explanation

I dont think you would need to track changes on the models, you would just
need adapters between the object.

I understand it would be another thing to maintain which would require more
time.  I just have a feeling that alot of people are duplicating the
adaptation portion of the code.

I may end up creating a nuget package with mappers in the for simplicity.
Are you guys open for pull requests?

**Comment by ob-stripe** [comment]
> Are you guys open for pull requests?

Certainly! For something like this, I would recommend submitting a "proof of concept" PR for just one or two resources so we can give feedback on the approach.

**Comment by granthoff1107** [comment]
So I recieved an answer on stack overflow which would simplify things if
that was the case.

What is the behavior of an optional field on an update?  If I omit the
field will the previous value stay the same?

Or will the values be cleared see this for reference
 https://stackoverflow.com/a/56980278/1938988

**Comment by ob-stripe** [comment]
> What is the behavior of an optional field on an update?  If I omit the field will the previous value stay the same?

Yes! In fact you're expected to only provide values for the field(s) you want to update. (Not that sending the same value for a field in an update request would break anything, it's just not necessary.)

**Comment by granthoff1107** [comment]
Wow, if that's the case it makes things a whole lot simpler.  The only
thing I'm confused on now is how do you handle the case where someone wants
to explicitly null a value?

**Comment by ob-stripe** [comment]
So right now the library doesn't have great support for this, and you'd have to use the `AddExtraParam` method to manually set the parameter to `null`.

E.g. this would unset the `shipping` value on a customer object:
```c#
var options = new CustomerUpdateOptions();
options.AddExtraParam("shipping", null);
customerService.Update("cus_123", options);
```

Obviously this is awkward, so we're going to fix this in the next major version (cf. #1662). You will be able to do something like this instead:
```c#
var options = new CustomerUpdateOptions
{
  Shipping = EmptyParam.Empty,
};
customerService.Update("cus_123", options);
```

**Comment by granthoff1107** [comment]
Okay so thanks, so basically if its null, the service doesn't serialize.
So to clear it you need to explicitly set it.  Thanks that makes things
simple

**Comment by ob-stripe** [comment]
Yes, that's exactly it. Null values in options classes are ignored by the serializer: https://github.com/stripe/stripe-dotnet/blob/fe3407b29bb9d734215d9007f1efd030b49748ea/src/Stripe.net/Infrastructure/FormEncoding/FormEncoder.cs#L214-L219

**Comment by granthoff1107** [comment]
Perfect,  thanks for the help.  You guys are doing a great job. It's rare
that I get to work with an Api that has such great support
