### ISSUE TITLE
Can't Remote Build (ms app center) with latest nuget: Could not AOT the assembly

### ISSUE THREAD

**Issue by ThomasAdrian** [stripe/stripe-dotnet#1729]
We're trying to use the latest nuget 27.20.0 for the latest SCA code using 3DS2 in a Xamarin Forms project, however remote builds on ms app center gives us a build error (local builds are ok):

MTOUCH : error MT3001: Could not AOT the assembly '/Users/vsts/agent/2.154.3/work/1/s/RoundApp/RoundApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/3-Build/Stripe.net.dll'

Regressing to and older version (25.19.1) works but we really would like the latest functionality.
Any ideas?

**Comment by ob-stripe** [comment]
Hi @ThomasAdrian. I'm not sure how much help we can provide here -- we don't officially support Xamarin and the library is not tested against it.

However, I've done some research on this specific error message and as far as I can tell, it's more of an issue with Xamarin itself than with the library, and it looks like this is fixed in recent versions of Xamarin.iOS. The fact that you can build locally but not on App Center could be due to the fact that your local version of Xamarin.iOS has the bug fix but the one on App Center does not.

Unfortunately it's hard to tell why older versions of Stripe.net do not cause this issue but recent versions do. The threads I found did not include much information regarding what exactly triggers the bug, and we rewrote large parts of the library in the last major version (27.0), so it could be any number of things.

My recommendation is to check the versions of Xamarion.iOS that you're using locally and on App Center, and ensure they match if possible. I am not familiar with App Center so I don't know how much control you have on the version running on their servers, you might need to ask their support for help there.

**Comment by ThomasAdrian** [comment]
Thanks @ob-stripe for your input I’ll update if we find a resolution or anything else

**Comment by rattrayalex-stripe** [comment]
Closing for now, since we don't intend to take any action here, but if you find something we can fix let us know!

**Comment by umair-me** [comment]
For me version `26.1.0` worked fine.
