### ISSUE TITLE
Checkout.Session Customer field is a string in Json, but Customer object required to Parse?

### ISSUE THREAD

**Issue by woodss** [stripe/stripe-dotnet#1753]
I'm trying to read the result of a Webhook notification - specifically, I need to get the customer field back after the payment has been made.

However, I am unable to do so because although I successfully get the customer token back in the Json, in order to parse it the code requires a Customer object.

`var session = stripeEvent.Data.Object as Stripe.Checkout.Session;

All good - I then attempt to retrieve the customer from the session Object:

var service = new CustomerService();
var customer = service.Get(session.Customer);
![image](https://user-images.githubusercontent.com/245552/63285415-95363800-c2ad-11e9-843d-0b56f2622333.png)

My Json response is parsing correctly into the object, as you can see:
![image](https://user-images.githubusercontent.com/245552/63285552-e34b3b80-c2ad-11e9-995e-a2edce8e0087.png)

Incidentally, in the Stripe.Checkout.Session object, why does it have a JsonIgnore attribute?
![image](https://user-images.githubusercontent.com/245552/63285629-155c9d80-c2ae-11e9-9f3d-8707bc1dbdda.png)

**Comment by remi-stripe** [comment]
@woodss This property is [expandable](https://stripe.com/docs/api/expanding_objects). This means that while the API returns the customer id as a string by default, you can fetch the Session and expand the whole Customer object in one call.

All expandable properties are implemented the same way in the library where there's a property for the ID of the object and another one for the full expanded object if present. What you want here is to access `CustomerId` on the Session: https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/Checkout/Sessions/Session.cs#L51

**Comment by woodss** [comment]
Thanks for coming back to me as I'm aware this is not a support forum - I'm still confused though because the Json that's coming back for me has an ID specifically in the Customer field - not an expandable Customer object.

`{
  "id": "evt_1F9DbUHwAut8agvT5WPjuDd4",
  "object": "event",
  "api_version": "2019-08-14",
  "created": 1566231668,
  "data": {
    "object": {
      "id": "cs_test_tKzEfVDNiY[REDACTED]",
      "object": "checkout.session",
      "billing_address_collection": null,
      "cancel_url": "[REDACTED]",
      "client_reference_id": null,
      **"customer": "cus_FeWeRF4ByksPN3",**
      "customer_email": null,
      "display_items": [
        {
          "amount": 1299,
          "currency": "gbp",
          "custom": {
            "description": "[REDACTED]",
            "images": null,
            "name": "[REDACTED]"
          },
          "quantity": 1,
          "type": "custom"
        }
      ],
      "livemode": false,
      "locale": null,
      "payment_intent": "pi_1F9Db5HwAut8agvTBjqOSB9c",
      "payment_method_types": [
        "card"
      ],
      "submit_type": null,
      "subscription": null,
      "success_url": "[REDACTED]"
    }
  },
  "livemode": false,
  "pending_webhooks": 1,
  "request": {
    "id": null,
    "idempotency_key": null
  },
  "type": "checkout.session.completed"
}------------------------------
`

Any attempt to access the object, for instance as Customer.EmailAddress results in a null reference error because apparently Customer is null - but I cannot directly access Customer.ToString() to pass the ID from the Json into the CustomerService() object to retrieve customer data,.

Worth mentioning that the customer is being created successfully on Stripe, and I can view all data - for some reason it is not populating into the Checkout Session though.

**Comment by remi-stripe** [comment]
@woodss This is expected behaviour. That's what I tried to explain earlier but I think I was unclear.

By default, `customer` is a string set to the id of the Customer. So when you fetch a `Session` object in the API (or in an Event), you always just see the customer id and not the customer's details. This makes the API faster as it doesn't need to expand one (or 10) related objects.

If you want to see the full customer object, it is possible, because it is expandable. This feature is documented here: https://stripe.com/docs/api/expanding_objects This lets you explicitly tell our API "I am fetching the Checkout Session but please also return the full Customer object so that I don't need to make a separate API request". You do this by passing `AddExpand` when you fetch the Session.

In Events though, you have no control over what to expand, this is just not possible. When we send an event about an object to your webhook endpoint, we always send the object without any expansion.

In the event here you can see `customer: "cus_FeWeRF4ByksPN3"`. This is that customer's id. It was created by Checkout and you can fetch that customer via the API separately using https://stripe.com/docs/api/customers/retrieve but only after extracting the customer id fromt eh event, by looking at the `CustomerId` property and **not** `Customer` since that one is null as the object is not expanded.
