### ISSUE TITLE
Cancel a subscription schedule removes it from the system

### ISSUE THREAD

**Issue by CarlosTorrecillas** [stripe/stripe-dotnet#1817]
I'm using the following code to cancel a subscription that is scheduled in the system:

```
var canceled = false;

try
{
    var subscriptionScheduleCancelOptions = new SubscriptionScheduleCancelOptions
    {
    };

    var subscriptionSchedule = await _subscriptionScheduleService.CancelAsync(id, subscriptionScheduleCancelOptions);

    if(subscriptionSchedule != null && 
        subscriptionSchedule.Status == "canceled")
    {
        canceled = true;
     }
 }
catch (Exception ex)
{
    Logger.Error(ex, $"Error cancelling subscription schedule id={id}");
}

return canceled;
```

The subscription then disappears from the system and it does not show up under the cancelled column. I would have expected it to be searchable in the dashboard and placed like the canceled subscriptions, under the canceled tab.

Is there any option that I'm missing here?

**Comment by CarlosTorrecillas** [comment]
Examples: 
sub_sched_1FW0ynGpwI99htqj3Anskiyv
sub_sched_1FW0ynGpwI99htqj3Anskiyv

They both were created in the system and as soon I did cancel them, then dissapeared. Currently talking to support but they don't seem to be able to find them out

**Comment by remi-stripe** [comment]
@CarlosTorrecillas This wouldn't be a bug with the stripe-dotnet library and seems to be a question about the API itself. I'm going to close this out as you're already in talks with our support team and they will be able to help you investigate this.

**Comment by CarlosTorrecillas** [comment]
They couldn't find anything and hoped you could assist. Is there anything you can check in the system?

Thanks

**Comment by CarlosTorrecillas** [comment]
and by the way it seems weird that a canceled schedule is not listed under the canceled tab, don't you think?

**Comment by remi-stripe** [comment]
Github issues should be limited to bugs with the libraries. I can't really discuss anything specific to your account here. Talking to our support team is the best approach to get this unblocked for you. I recommend mentioning this github issues and that you talked to me and they'll be able to help you.

In terms of API, this usually happens when the schedule has not started the Subscription yet, for example when the start of the first phase is in the future and there's no Subscription ready yet.
