### ISSUE TITLE
List Products,  Filter By Metadata

### ISSUE THREAD

**Issue by hatoro** [stripe/stripe-dotnet#1844]
I am looking to filter my list of products by metadata, which is not included  in ProductListOptions class.  During my research I stumbled upon ExtraParams property but that does not help.

**Comment by remi-stripe** [comment]
@hatoro Today, the API does not support listing by metadata. It's just not a feature that has been built yet. That's why the library does not support it. It's a feature request we've heard of before but no short term plans to ship this. I'd recommend reaching out to our support team: https://support.stripe.com/contact

I'm going to close this out as github issues should be limited to bug with the library itself. If the feature was added to the API we would also ship it in stripe-dotnet.
