### ISSUE TITLE
Extend documentation for CustomerService.List with ExtraParams

### ISSUE THREAD

**Issue by thomasgalliker** [stripe/stripe-dotnet#1858]
I couldn't find any documentation of how to use `CustomerService.List` method in conjunction with CustomerListOptions' `ExtraParams` in Stripe's API documentation. After playing around with the API, I came up with following unit test.

Do you think we can extend the API docs in order to illustrate how to use ExtraParams? It is yet unclear to me, if I can use metadata key in the ExtraParams. Things like that should be documented I think.
```

        [Fact]
        public void ShouldReturnCustomerByEmail()
        {
            // Arrange
            IDictionary<string, object> extraParams = new Dictionary<string, object>
            {
                { "email", "thomas@bluewin.ch" }
            };

            var customerService = new CustomerService();

            // Act
            var customer = customerService.List(new CustomerListOptions() { Limit = 1, ExtraParams = extraParams }).SingleOrDefault();

            // Assert
            customer.Should().NotBeNull();
            customer.Email.Should().Be("thomas@bluewin.ch");
        }
```

**Comment by remi-stripe** [comment]
@thomasgalliker The reasons we don't actively document is ExtraParams is that no one should need this feature for their integration. We built this as a way to pass secret parameters to the API in some exceptional cases such as when building a private beta and having a dotnet user that needs to pass the information.

All officially supported API parameters are already in the library. For example, if you want to list customers via their email address you would use the official `Email` [parameter|https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Customers/CustomerListOptions.cs#L8] like this:

```
var options = new CustomerListOptions
{
  Email = "test@example.com",
};
var service = new CustomerService();
var customers = service.List(options);
```

We support all the properties and parameters you see in the API reference and you can entirely ignore `ExtraParams`.

As for listing via metadata, this is not something the API supports today which is why it's not in the library.

**Comment by thomasgalliker** [comment]
Ok, interesting. Marking such properties as internal or giving a comment "Internal use only" would have helped 👍
