### ISSUE TITLE
Staying up to date?

### ISSUE THREAD

**Issue by Andrewangeta** [stripe/stripe-dotnet#1868]
This might not be a direct issue with the .NET library but it apples to open source stripe libraries.
I maintain [StripeKit](https://github.com/vapor-community/StripeKit) and I often find it cumbersome to know when endpoints have been updated with new or removed request parameters. I just spent the past week going through every API endpoint and route in the API docs to verify/update any new/removed fields I might have missed during major API upgrades. Is there any mechanism/way to be notified if a parameter name changes or if a new field was added to API resources? 

This would help a lot with keeping pace with the other libraries and make it easier to update and react to small changes easily. Thanks!

**Comment by remi-stripe** [comment]
@Andrewangeta Thanks for reaching out, that's definitely a question we've been thinking about a lot recently. Today we have the [upgrades documentation](https://stripe.com/docs/upgrades#api-changelog) that lists all breaking changes we release which are always behind an API version. This would be a good thing to monitor in that case.

For backwards compatible changes though such as new properties or parameters, we don't publish a changelog today unfortunately. I maintain one internally and we're hoping to ship it publicly next year (though no firm guarantee just yet).

What you can do though is watch the [stripe/openapi project](https://github.com/stripe/openapi) directly. It contains the spec for our API (and related fixtures) and we use it to automatically generate some of our client libraries like stripe-java or the Typescript definitions for stripe-node which we're actively working on. This repo gets updated every time we ship a new feature since it's required to release those libraries.

Today we don't version that repo but we have been thinking about adding releases and tags to more explicitly surface what changed and what is a breaking change. Would you be able to try this for a bit to see if it helps you keep track of changes?

**Comment by Andrewangeta** [comment]
@remi-stripe Cool thanks for responding! And id like to keep track with the openapi project. I just have to look up how to generate the spec files to see the routes etc. and keep up to date. Is there a way to generate a html style doc from the spec? if so where would I find that. Or a better question is how do you check out the changes from he openapi spec or can you just talk to the other engineers haha?

**Comment by remi-stripe** [comment]
@Andrewangeta I don't know of an easy way to generate an HTML view of the spec unfortunately. The spec is not too hard to read once you get used to it, especially when focusing on what changed and with some context.

The alternative otherwise would be to follow the stripe-dotnet or stripe-java project. We open PRs and merge them every time some new feature ships and the code is definitely easier to grasp than the spec itself so you'd just have to mirror what we do on our side otherwise.

**Comment by Andrewangeta** [comment]
Yea that's what I was probably gonna try to do. I should watch this repo take notes of what's gonna change before I update the library etc. This was helpful Just one more question:
What's the requirement for stripe libraries where you send a special header for every request with the application name or something like that? I can't remember.

**Comment by clement911** [comment]
@remi-stripe will the Stripe.dotnet be codegen'ed with this spec as well?
Wondering if you have a timeline and/or if you expect the current lib to change a lot as a result or if the generated lib will be closely matching the current code?

**Comment by remi-stripe** [comment]
@Andrewangeta We have a partner program and you can read more about it here: https://stripe.com/partner-program
You can also self-report your library by looking at how we report our own libraries such as the PHP one [here](https://github.com/stripe/stripe-php/blob/3371f2adfcab23d859658a0130943c9286434d23/lib/ApiRequestor.php#L258)

@clement911 At the moment the library is still manually maintained. We are planning to codegen the library, hopefully next year.
There will likely be breaking changes when we do mostly to make the library as consistent as it should be but we also aim to match as much of the existing state as possible when codegen-ing for the first time.

**Comment by clement911** [comment]
Got it, thanks for the quick response!
