### ISSUE TITLE
What are the 'Deleted' properties for?

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1870]
These are not documented AFAIK.
I also triggered a customer deletion and inspected the event's payload. Even then, I found no `deleted` property.
So what are they for?

**Comment by remi-stripe** [comment]
@clement911 If you delete a Customer, the response you get back from the API only has a handful of properties (Id, Object and Deleted are set, nothing else) and looks like this:
```
{
  "id": "cus_ABCD",
  "object": "customer",
  "deleted": true
}
```

The properties lets you know that so that you don't try to access other properties that would not be set anymore. This applies to all the objects in the API that can be deleted.

**Comment by clement911** [comment]
Got it thanks.

Quick question, would the `deleted` webhook payload be the same (just id, object and deleted) or would it be the full object payload before it was deleted?

**Comment by remi-stripe** [comment]
The event would have the full object from before it was deleted and you know it's being deleted because the event is `customer.deleted` in that case!

**Comment by clement911** [comment]
Perfect, thanks!
