### ISSUE TITLE
UsageRecordService doesn't implement INestedListable

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1871]
Is this endpoint not implemented?

![image](https://user-images.githubusercontent.com/3426504/70248826-cd3d8a00-177b-11ea-8b9b-208f7b4b45d6.png)

**Comment by karlr-stripe** [comment]
Hi @clement911  — this endpoint is implemented in the [UsageRecordSummaryService](https://github.com/stripe/stripe-dotnet/blob/2137391a57a66e767ac110dd6c2f6636af9ad69b/src/Stripe.net/Services/UsageRecordSummaries/UsageRecordSummaryService.cs) — you'll find documentation for this in the [API reference](https://stripe.com/docs/api/usage_records/subscription_item_summary_list?lang=dotnet).

I'm going to close out this issue as it's not a bug with stripe-dotnet, but hopefully this helps!

**Comment by clement911** [comment]
Oh I see, I got confused because it's documented as a single service in the docs but it's 2 different service in Stripe.Net.
Is that because there are 2 different base paths?

**Comment by karlr-stripe** [comment]
I believe this was mainly done because while UsageRecordService primarily deals with the UsageRecord model(creating them etc.), UsageRecordSummaries are different in shape and design and thus a different model, so they'd use a separate service. The underlying API's nested endpoint that returns a different object than the top-level endpoint in this case was chosen to be modelled this way in this library.

**Comment by clement911** [comment]
Got it thank you.
Btw I'm quite new to stripe and stripe.net but from what I've seen so far this library looks fantastic 👍

**Comment by remi-stripe** [comment]
@clement911 That's so great to hear, thank you for the positive feedback! If you see anything else confusing about the library, please let us know!
