### ISSUE TITLE
Impact of account API version for stripe.net

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1873]
This is more of a question that an issue.
I'm trying to clarify the impact of changing our account's API version.

As far as I can see, Stripe.net **ALWAYS** provides the `Stripe-Version` header, so my understanding is that upgrading our account version will have no impact on any calls issued via Stripe.net.

The only thing this would impact is that any new events and webhook requests generated would be issued with the new account's version, but all outbound calls will keep on using whatever version is used by Stripe.net (and I understand we can override it on a per request basis as well).

Did I get that right?

**Comment by remi-stripe** [comment]
When changing an API version in your account, it changes three things:
- Events sent to your webhook endpoint are formatted based on that API version unless you explicitly pin your endpoint to a given [API version](https://stripe.com/docs/api/webhook_endpoints/create#create_webhook_endpoint-api_version) which I mentioned in another issue. When using stripe-dotnet we highly recommend doing this.
- API requests made by your code will use that API version unless you explicitly pin the request to an API version. In your case, stripe-dotnet always pins every API request so this would never affect you. You also can never change the version yourself in a request since stripe-dotnet is typed and requires an exact API version.
- If you use our Billing products, all calls will use that API version when paying invoices for example. This can affect default statement descriptors or some operations you'd be allowed to do in the Dashboard.

I also wanted to mention that Github issues should really be limited to feature requests or bug reports about the library itself. Since you have a lot of high level questions, I'd recommend either contacting our [support team](https://support.stripe.com/contact) or joining Stripes and developers on IRC on Freenode in the #stripe channel where you could get some real time help and discuss all of those with us and other Stripe users.

**Comment by clement911** [comment]
Thank you so much for your all your quick answers.
I really wish there was an open Stripe forum for people to discuss these kind of things.

**Comment by remi-stripe** [comment]
Sorry to hear that. We're there all weekdays usually and are in the channel right now if you want to come ask some questions!
