### ISSUE TITLE
Listing all entities in chronological order

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1875]
I want to list all entities (let's say Customers) in chronological order.

My understanding is that:

-  If I use `StartingAfter`, then paging will occur in chronological order
-  If I use `EndingBefore`, then paging will occur in **reverse** chronological order

1) So, I would want to use `StartingAfter` but my issue is that I don't know how to retrieve the first page? (the "oldest" page)
If I set both `StartingAfter` and `EndingBefore` to null, then it seems that Stripe defaults to reverse chronological order and returned the most recent page.
So I guess I must pass something to `StartingAfter`, but what exactly?

2) Also, is the chronological order always defined with the `Created` property? In which case, does it mean that all `IListable` entities have a `Created`?

Sorry for all the questions, I've learned so much already and it's important for me to get things right as we're making quite a big bet on Stripe's API.

**Comment by remi-stripe** [comment]
@clement911 At the moment, this is not something our API supports. We don't let you start from the oldest object and go back to the most recent. If you're paginating to store objects, then you should be able to start from the most recent and go through the whole list and cache this in your database for example. This would let you iterate only on new objects in the future as you'd remember the most recent object you had seen last time and stop paginating at that point.

I don't think every listable entities have a `Created` property. `Card` for example (which is legacy) can be listed on a customer and does not have that property but it's because it's cards for a given customer where we made the default one the first in the list. That's more of an edge case though and not something you should worry about.

**Comment by clement911** [comment]
Got it.
I can work with that. We'll just paginate from new to old.
For new entities, we shouldn't even have to query since we'll set up some a webhook before starting the pagination.

One advantage of going from old to new is that you can roughly know how many pages are left between the current page and the last page (based on the remaining number of days between the `created` value in the current page and the time as of now). Let's say today is the 31st of december and the oldest entity has a created value of 1st of Jan. By the time we are on the page where items have a created value of 30th June, we know that we have roughly loaded 50% of pages.

Of course, it's approximate but it's quite useful for us. Ideally Stripe would offer a `/v1/customers/count`. It would be more accurate but I don't think it exists. 

Please let me know if you know of any other mechanisms to estimate the average percentage completion of the pull pagination.

**Comment by remi-stripe** [comment]
That's fair but most businesses grow over time (hopefully at least) so when you're in the middle of the year, you're usually less than 50% of the way there, hopefully even less than 10%!

Also, if you're trying to ingest historical data, you might be better off exporting data from the Dashboard to a CSV or similar and parsing that information instead!

We don't have plans to support a count feature at the moment. Those can be really costly to calculate and cause pretty serious latency issues and it's something we've deprecated years ago.

**Comment by clement911** [comment]
Got it.
Unfortunately we can't rely on CSV.
We're building Connect integration so the import needs to be fully automated.
