### ISSUE TITLE
Handling retries for HTTP 429 Too Many Requests

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1886]
If Stripe returns HTTP 429, I want threads to implement exponential back off.

I see that Stripe.net already implements a back off mechanism, but it's not clear to me if it applies to HTTP 429 or only to HTTP 5xx.

Does Stripe include `Stripe-Should-Retry: true` when it returns a 429?
Are we supposed to handle 429 retries ourselves?

https://github.com/stripe/stripe-dotnet/blob/2666581d3fecb44fbe80d1344a846d75c5099feb/src/Stripe.net/Infrastructure/Public/SystemNetHttpClient.cs#L254-L285

**Comment by remi-stripe** [comment]
@clement911 At the moment we don't retry real rate limits (the ones where you make too many requests) because retrying would just cause even more requests. We do retry a subset of rate limits (the ones we call [lock timeouts](https://stripe.com/docs/rate-limits#object-lock-timeouts)) as they are likely to succeed after a retry.

I would recommend handling 429s yourself since a lot of it requires some custom business logic to decide which parts of your integration should slow down first.

**Comment by clement911** [comment]
Understood.
It's a bit of a shame that we have to re-implement a backoff strategy ourselves but you raise a good point that _"it requires some custom business logic to decide which parts of your integration should slow down first"_.
