### ISSUE TITLE
Invalid email

### ISSUE THREAD

**Issue by bigrbuk** [stripe/stripe-dotnet#1897]
.NET Framework 4.6
Stripe.NET 29.3

Getting an invalid email error when supplying CustomerEmail in a Checkout Session for a valid email address.

Address of format a.names@domainabc.ca

**Comment by remi-stripe** [comment]
@bigrbuk Almost always, the issue is due to a trailing space at the beginning or end of the email address rendering it invalid. Make sure you strip all your emails from those spaces. If it's still failing after that, I'd recommend reaching out to our support team instead here: https://support.stripe.com/contact
