### ISSUE TITLE
Maintainability / backward compatibility

### ISSUE THREAD

**Issue by Thorium** [stripe/stripe-dotnet#1904]
The library should keep maintainability and backward compatibility better than it has done.

I've been working with Stripe.NET integration for a few years now, and one thing that is quite annoying is that you seem to do breaking change renaming very often. 
The correct naming may be a value for your internal team, but it is a cost to customer, to always modify the source-code, going back and forth (e.g. between "StripeSourceService" to "Stripe.SourceService", and "ReportRun.ParametersOptions" to "ReportRunParametersOptions").

I hope you'd consider the naming bit better in the initial release, if it's so important to you. As for a customer, the backward compatibility is more important than names of the classes and methods. 

We can see from the NuGet package statistics that the package 10.4.0 had 133,971 downloads, and after that, the downloads have been spreading over the 24 next major releases. So probably many customers have failed to keep-up with the major release cycle. 

That is sad, because this library deals with money, and if there is any security issues fixed, the library should be up-to-date. Otherwise a hacker could read the open source code and exploit any vulnerability.

So many major release braking changes makes also testing and issue tracking painful.

The non-breaking minor versions you can release as often as you want. I understand that Stripe is "a start-up company", but keep in mind you are also a financial corporation, so I wish a bit more professionalism and consideration here, before doing pointless refactorings that cause more technical work for the customers without adding a business value.

**Comment by remi-stripe** [comment]
@Thorium Thanks a lot for the thoughtful feedback here, we really appreciate this. I'll try to clarify a bit how we're approaching this, I hope this will help!

One thing that is important to note with stripe-dotnet is that the library is pinned to a specific API version. This is similar to our other typed libraries [stripe-go](https://github.com/stripe/stripe-go) and [stripe-java](https://github.com/stripe/stripe-java) and recently the release of Typescript definitions in stripe-node. This is required as API versions add or remove core parameters or properties in the API, but can also change the shape of an object entirely such as a field being renamed, its type changing from a boolean to an enum/string, or a hash/dictionary changing shape.

As the library is pinned to an API version, supporting the newest one always requires a major version of the library to be released. If we did not do that, you would upgrade the library between minor versions and get new behavior such as changing the way [statement descriptors work](https://stripe.com/docs/upgrades#2019-02-19).

Looking at our [changelog](https://github.com/stripe/stripe-dotnet/blob/master/CHANGELOG.md) most of the recent major versions were linked to a change in the default API version or to a real change that could break deserialization with the library. The main one that diverge from that pattern is [32.0.0](https://github.com/stripe/stripe-dotnet/blob/master/CHANGELOG.md#3200---2019-10-18) which contained large naming changes to the library.

Now, for the class renames, we definitely agree that this can be problematic. We do try to group changes together, like we did in [32.0.0](https://github.com/stripe/stripe-dotnet/blob/master/CHANGELOG.md#3200---2019-10-18) to make the library easier to use and more consistent without making the upgrade itself intractable. This works well when you regularly update the library but it does make this really complex when you are a few major versions behind.

A lot of our work over the past year has been to prepare all our libraries to be automatically generated from the [OpenAPI spec](https://github.com/stripe/openapi). We already do this for some of our languages (ruby, python, node and java) and are almost done with PHP. We also use the same tooling to generate examples in our [API reference](https://stripe.com/docs/api) to ensure that they match the exact shape the library expects.

For years, all of this work was done by hand, leading to many inconsistencies such as incorrect namings like the ones you mentioned that we are fixing, but also missing or incorrect features, or examples that don't match what the library supports. A lot of the recent renames have been made to prepare the library for code generation to ensure we're ready to scale it as our products and our API continue to grow and expand this year.

One of our long term goals would be to support generating the library for a specific API version but with all the backwards compatible changes bundled in. The idea would be getting the latest parameter or property we shipped, but with the current API version you're building against and none of the breaking changes due to newer API versions. 

I hope this provides a bit more context around the release process and how we're approaching this. I'd love to hear what you think about how we could better document this and what we could improve to help upgrades be smoother for developers either here or directly over email (I'm remi@stripe.com)!

**Comment by Thorium** [comment]
Hi Remi,

Thanks for the detailed reply.

So this issue should be raised to the API rather than the .Net-library?

**Comment by remi-stripe** [comment]
@Thorium I'm happy to chat more about the API if needed. The thing is that when we release a new API version, we don't deprecate older ones. We keep supporting those API version. We also ship most new changes in a backwards compatible way, so that even on an old API version you can still use new parameters or features.

The limitation here is that our client libraries in statically typed languages are pinned to the latest API version so we only push changes on newer versions and don't backport it, which wouldn't be possible manually.

**Comment by clement911** [comment]
Interesting discussion.
The rate of change in the API is definitely high but for our project we'd much rather that than not having access to the latest features.
Hopefully the code generation from the spec will lead to less errors/inconsistencies and less releases as a result.

**Comment by michaelkhalsa** [comment]
I would also like to make the same request, and it turned me off using the library.

For example, where previously i passed in the api key as a parameter, now it is through a new StripeClient, which is passed through the ctor. (that was an easy one to figure out.

Changing ChargeId to Charge, etc. While fine in a closed library, in a public library these kind of changes do not really add much to understand-ability (the ChargeID actually seemed better). The ExtraParams dictionary breaking its signature, but not in all places. 

What is not easy to figure out, is where i add customer address information when creating a charge token. Here is where a bit of documentation, or even a real world example would help a ton. (I am upgrading from like version 20 something to i believe it is ver 37. This was not because the earlier version did not work, rather removing the dependencies of the earlier version.

Maybe even consider multiple nugets if the breaking differences are too great because of changes to stripe apis???

Thanks for all of your work and dedication.

**Comment by remi-stripe** [comment]
@michaelkhalsa Thanks for all the feedback! I definitely agree that some of the changes might seem unnecessary and cosmetic right now. For a bit of context, we're actively working on automatically generating the code for stripe-dotnet from our public openapi spec internally. This will ensure that the library is always up-to-date and using the latest features. It will also ensure that we don't ship minor bugs by mistake due to human error when typing a specific property or parameter for example (which I've sadly done a few times in the past year despite having careful reviews). It also ensures that we support type changes better such as when a field becomes optional or nullable, which can sometimes cause issue during data deserialization otherwise.

We have automatically generated stripe-java for over a year now which has been really powerful and ensured the library is fully typed and feature complete. Now, to properly codegen the library, consistency in naming is really important since we want a unique and consistent way to name classes, properties and parameters. This is why we've tried to clean up as many of those inconsistencies as possible over the past few months as we get closer and closer to releasing the new version of the library.

We also make sure that we support older patterns for multiple major versions. For example, you can still set the API key globally even though we have deprecated this for many major versions, just because we know many developers find this approach easier.

We do try to document as many of the breaking changes as possible on our wiki here: https://github.com/stripe/stripe-dotnet/wiki Have you found that this was helpful? Do you have ideas of better ways we could do this?

**Comment by remi-stripe** [comment]
I wanted to send a quick update on this thread. We have released two new major versions, v38 followed by v39 which have a lot of breaking changes and cleanup bundled in them.

With those changes, we were able to finish the project to codegen stripe-dotnet end to end. This means that, moving forward, the majority of the library will be automatically generated from our openapi spec. One huge benefit will be around consistency for naming and shape which should prevent the need for other breaking changes in the future to align on naming.

I do hope this makes it a lot easier to upgrade moving forward though it means having to go through a potentially painful upgrade for v38 as we've documented all breaking changes in https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-the-upcoming-v38

I'm going to close this out but please let me know if you have any follow up questions or feedback to share!
