### ISSUE TITLE
Invalid response object from API (SubscriptionService)

### ISSUE THREAD

**Issue by alpesh89** [stripe/stripe-dotnet#1907]
Get Invalid response object from API error when call the api.

```c#
var service = new SubscriptionService();
Subscription subscription = service.Create(SubscriptionOptions);
```

**Comment by cjavilla-stripe** [comment]
Hey @alpesh89 That argument to Create should be an instance of `SubscriptionCreateOptions`.

Can you elaborate on the error you're seeing? Also, I wanted to mention you may have quicker response times by reaching out directly to support: support.stripe.com/contact.

**Comment by alpesh89** [comment]
@cjavilla-stripe 
Here is my code to set up subscription:
var items = new List<SubscriptionItemOption> {
                      new SubscriptionItemOption {
                        PlanId = planId
                      }
                    };
                    var SubscriptionCreateOptions = new SubscriptionCreateOptions
                    {
                        CustomerId = customer.Id,
                        Items = items
                    };
                    var service = new SubscriptionService();
                    Subscription subscription = service.Create(SubscriptionCreateOptions);

Response from  service.Create():
{"Invalid response object from API: \"{\n  \"id\": \"sub_Ggssdr33dsf\",\n  \"object\": \"subscription\",\n  \"application_fee_percent\": null,\n  \"billing\": \"charge_automatically\",\n  \"billing_cycle_anchor\": 1580874573,\n  \"billing_thresholds\": null,\n  \"cancel_at\": null,\n  \"cancel_at_period_end\": false,\n  \"canceled_at\": null,\n  \"collection_method\": \"charge_automatically\",\n  \"created\": 1580874573,\n  \"current_period_end\": 1612496973,\n  \"current_period_start\": 1580874573,\n  \"customer\": \"cus_Gg0sdadhum30x\",\n  \"days_until_due\": null,\n  \"default_payment_method\": null,\n  \"default_source\": null,\n  \"default_tax_rates\": [\n\n  ],\n  \"discount\": null,\n  \"ended_at\": null,\n  \"invoice_customer_balance_settings\": {\n    \"consume_applied_balance_on_void\": true\n  },\n  \"items\": {\n    \"object\": \"list\",\n    \"data\": [\n      {\n        \"id\": \"si_Gg0vIasdasdd6PfK4\",\n        \"object\": \"subscription_item\",\n        \"billing_thresholds\": null,\n        \"created\": 1580874573,\n        \"metadata\": {\n        },\n        \"plan\": {\n          \"id\": \"plan_GfQNbdEojq4fLn\",\n          \"object\": \"plan\",\n          \"active\": true,\n          \"aggregate_usage\": null,\n          \"amount\": 10000,\n          \"amount_decimal\": \"10000\",\n          \"billing_scheme\": \"per_unit\",\n          \"created\": 1580738619,\n          \"currency\": \"cad\",\n          \"interval\": \"year\",\n          \"interval_count\": 1,\n          \"livemode\": false,\n          \"metadata\": {\n          },\n          \"nickname\": null,\n          \"product\": \"prod_GfQNuTLOCwG3oY\",\n          \"tiers\": null,\n          \"tiers_mode\": null,\n          \"transform_usage\": null,\n          \"trial_period_days\": null,\n          \"usage_type\": \"licensed\"\n        },\n        \"quantity\": 1,\n        \"subscription\": \"sub_Ggtr5rQNWm1\",\n        \"tax_rates\": [\n\n        ]\n      }\n    ],\n    \"has_more\": false,\n    \"total_count\": 1,\n    \"url\": \"/v1/subscription_items?subscription=sub_Gg0v5eeroQNWm1\"\n  }, .......

**Comment by remi-stripe** [comment]
@alpesh89 Are those the exact ids we return in the API? I looked for all of those object ids like the customer, subscription or subscription item id and none of them seem to exist in our systems so I'm a bit confused.

I can also see that you are likely using an older version of stripe-dotnet since you pass `PlanId` which was renamed a while ago. 

Would you be able to send an example request id (req_123) that is associated with your request? Is it possible you're using some mocking system or similar that returns a "fake" subscription that wouldn't have a good shape?

**Comment by alpesh89** [comment]
@remi-stripe I'm using 29.1.0 version. Right now I'm testing the application for Test Data. 

To make it work, Should I upgrade the stripe API?

**Comment by remi-stripe** [comment]
@alpesh89 There's no need to upgrade the API no. The problem is that I can't find your requests so I can't easily see what could be causing the issue. Can you send an exact request id (req_123) as returned by this error? You can also look up the logs in your Dashboard directly here: https://dashboard.stripe.com/test/logs

**Comment by alpesh89** [comment]
Here is the detail I found:
ID : req_jJHAfGjQphznCx

charge — ch_1G8etNA0zv8m4ex8w11H4oWF
<https://dashboard.stripe.com/test/payments/ch_1G8etNA0zv8m4ex8w11H4oWF>
customer — cus_Gg0vC5aChum30x
<https://dashboard.stripe.com/test/customers/cus_Gg0vC5aChum30x>
subscription — sub_Gg0vkKe3oQNWm1
<https://dashboard.stripe.com/test/subscriptions/sub_Gg0vkKe3oQNWm1>
plan — plan_GfQNbdEojq4fLn
<https://dashboard.stripe.com/test/plans/plan_GfQNbdEojq4fLn>

**Comment by remi-stripe** [comment]
thanks, that's exactly what I needed. So I went and looked at that query and I don't see anything that could explain the problem. I then copied the exact raw JSON that you get back from that API request and I'm able to successfully deserialize this resource with stripe-dotnet 29.1.0 (your exact version).

To me, this means that there's something else that is interfering with the data we send you and that it's changing the shape of the JSON causing the library to fail while deserializing it.

What I would recommend here is trying the latest version of the library first, to see if that solves the issue. Separately, I would also recommend reaching out to our support team directly with a lot more details about your current set up and the exact raw response that our API returns so that we can compare the data more actively.

**Comment by alpesh89** [comment]
Ok, Thank you @remi-stripe

**Comment by alpesh89** [comment]
Hi @remi-stripe, It worked in latest version.

**Comment by remi-stripe** [comment]
Can you also try 29.6.0 and 30.0.0? I'm trying to narrow down which change could cause this though the fact that I can deserialize the JSON our API returns to your request, in 29.1.0 points to something else being wrong.

**Comment by alpesh89** [comment]
I tried both versions:
29.6.0: Got failed response same as 29.1.0
30.0.0: Success (It worked)

**Comment by remi-stripe** [comment]
@alpesh89 Thanks a lot for the extra details. Unfortunately we can not seem to reproduce this at all locally, even with the exact raw JSON our API returns to you in the request you shared. I'm a bit at a loss here.

Would you be able to move to 30.* or even the latest on your end?

**Comment by alpesh89** [comment]
Sure, I'll move to latest version.

**Comment by remi-stripe** [comment]
Thanks for being flexible, and let us know if you see anything else!
