### ISSUE TITLE
ListAutoPaging async version

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1946]
Would it be possible to create an async version of ListAutoPaging?
I don't see why not?

It could return a `Task<IEnumerable<T>>`.

Or, if the concern is to not load the entire list in memory, then it could still be implemented using c# 8 [async streams](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#asynchronous-streams), behind a .NET Core 3.x and .NET Standard 2.1 version flag.

What do you think?

**Comment by clement911** [comment]
Or I guess it could return a `IEnumerable<Task<IEnumerable<T>>>`

**Comment by remi-stripe** [comment]
@clement911 Can you give a bit more context around how you would automatic pagination in an async context exactly?

**Comment by clement911** [comment]
I would like to call it like this:

`var entireList = await service.ListAutoPagingAsync(listOptions)`

**Comment by remi-stripe** [comment]
@clement911 Gotcha, so you don't really want async per se and you mostly just want autopaging to paginate through the entire list? Because that's not what auto pagination does. What it does instead is, as you iterate over the elements, fetch the next page automatically for you once you access the last one.

I don't think we would add a method that lets you possibly paginate millions of objects making hundreds of thousands of API requests behind the scenes. That call could also take hours to complete.

**Comment by clement911** [comment]
But that can already be achieved by calling `.ToArray()` or `.ToList()`, to force the pagination of all pages into a single list.

I wouldn't be doing that on a list that I know can be huge, but often I know in advance that the list size will be small, but potentially bigger than a single page.

For examples, imagine that I want to retrieve all the products.
I can have more than 100 products, but I know I won't have millions of products (it's possible maybe, but not usually), so I want to retrieve the entire list in an easy, async way.

Makes sense?

Adding an async version doesn't really change the fact that it's already possible to force pagination with a `ToList()`.

**Comment by ob-stripe** [comment]
Implemented in 35.11.0. All services that support `ListAutoPaging` now also support `ListAutoPagingAsync`.

This is only available for .NET Standard 2.0 (.NET Core 2.0 / .NET Framework 4.6.1). The asynchronous autopagination methods are not available when using .NET Framework <= 4.6.

**Comment by clement911** [comment]
Thank you!

**Comment by richardlawley** [comment]
@ob-stripe Upgrading to this caused my existing code (which calls ListAutoPaging from an async method) to deadlock.  I believe this is because you've changed your implementation of the sync ListAutoPaging to call the Async version with ToEnumerable.  It wasn't immediately obvious from the changelog that this had happened, so it took some time to track down.

I've resolved it myself by switching to the Async method and properly awaiting with it, but I suspect this may impact other people too.

**Comment by ob-stripe** [comment]
@richardlawley Thanks for the report. We'll have a fix out shortly.

**Comment by ob-stripe** [comment]
Version 35.12.1 should fix the deadlock issue.
