### ISSUE TITLE
Charge.Source expansion

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1975]
I just came across `charge.Source`, which is not documented as far as I can see.
Is it always / automatically expanded?

**Comment by remi-stripe** [comment]
It's a legacy field that we actively discourage you from using. It is automatically expanded but it's deprecated since we introduced `PaymentMethod` as a new API.

Ignore that field and instead use `PaymentMethodDetails` on Charge as documented [here](https://stripe.com/docs/api/charges/object#charge_object-payment_method_details)
