### ISSUE TITLE
Charge.Destination VS Charge.TransferData.Destination

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1977]
What is the difference or relationship between `Charge.Destination` and `Charge.TransferData.Destination`?

Only the latter is documented.

p.s: looks like the comments for `Charge.Destination` is wrong and was copied from the `OnBehalfOf` property.

**Comment by remi-stripe** [comment]
@clement911 `Destination` is the original shape of the feature (early 2015). It was split into 2 separate features 2 years later and `Destination` is now deprecated. It still works but it's undocumented so that no new developers use this, but we don't remove it from client libraries to avoid breaking existing integrations. On our newer API `PaymentIntent` there's only the 2 separate parameters instead.

I'm going to close this out! I would also recommend that you join us on IRC, we're on Freenode in #stripe and it would be a lot easier to answer questions like this one in real time. Otherwise, you can just email me directly (first name @stripe.com)

We do love the feedback about the library itself as it helps us improve it and make it better, but we should make sure that real "product questions" don't come through Github issues (which are limited to bugs and feature requests with the library itself).

**Comment by clement911** [comment]
Well, the field exists on the lib but not the API so I consider a potential lib-only question but I get your point.
Here is some feedback for Stripe.Net itself, have you considered marking these deprecated properties with the `[Obsolete('Some reason')]` attribute to make it self documenting?

**Comment by remi-stripe** [comment]
> Here is some feedback for Stripe.Net itself, have you considered marking these deprecated properties with the [Obsolete('Some reason')] attribute to make it self documenting?

We have, and we do this really often. We just don't want to introduce toil for developers that have had something working for many years, recommending they move to something they don't really need to do. We are not going to remove `destination` on `Charge` at all, it will stay forever. Instead, developers will move to `PaymentIntent` and use the new world over time.

It's a tricky balance between actively discouraging someone from using something that is going away soon (like if an API version change is coming and the next major will just remote the property) versus something that just works, it's just not the canonical path anymore.

An example of this is `Prorate` in the library. It used to be a boolean and now it's `ProrationBehavior` as an enum. We marked `Prorate` as deprecated because the new feature is a lot more powerful and it is worth moving to it even for existing integrations, even if `Prorate` will likely stick around for a long time. It's the same thing for `TaxPercent` versus `DefaultTaxRates`.

A lot of those changes we discuss extensively internally to find the right balance between changes that are worth warning existing developers about versus the ones that they will move to over time and should learn through other means such as the developer digest or our changelog.

**Comment by clement911** [comment]
Thanks for the comments.
I may appear to be nit picking but it's only the case because the overall library and API is already great!
