### ISSUE TITLE
Subscription.NextPendingInvoiceItemInvoice should be a DateTime?

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1981]
Shouldn't `Subscription.NextPendingInvoiceItemInvoice` be a `DateTime`?

**Comment by remi-stripe** [comment]
@clement911 Ah yes it definitely should, nice catch. I'll get it fixed in the next major!

**Comment by clement911** [comment]
Hi @remi-stripe 
Why do you close tickets like this immediately?
Shouldn't it happen only once it's fixed?
Otherwise it might slip though..

**Comment by remi-stripe** [comment]
I'm happy to reopen if you prefer. It's just a lot of noise to get numerous open issues for missing properties and we manage this differently internally.

**Comment by remi-stripe** [comment]
just clarifying that I had fixed it immediately in https://github.com/stripe/stripe-dotnet/pull/1961/files#diff-fa4526dc56a06afcab4a68ee50731515R265 which is going in the next major

**Comment by clement911** [comment]
oh next major sorry. I saw a few releases since but didn't realize they were minor only and that fix was going in the next major.

I guess when I see an issue closed, I would expect it ready in the package already...

**Comment by remi-stripe** [comment]
Yeah that's totally fair. I am trying to close them because we don't often do majors for small breaking changes. We do them for API version changes or large scale changes (like the one coming this week). I wanted to avoid having 10+ open issues for a few days or a few weeks just because we're waiting on the major to be released, especially as they are small inconsistencies.

**Comment by remi-stripe** [comment]
This has been released in 36.0.0

**Comment by clement911** [comment]
thank you!
