### ISSUE TITLE
Methods take optional options even though parameters are required

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#2002]
The following List APIs all have at least 1 required parameter, yet Stripe.net `ListOptions` parameter is optional.

`/v1/payment_methods`: customer,type
`/v1/radar/value_list_items`: value_list
`/v1/subscription_items`: subscription

p.s: I would have thought these would be 'nested services', with the parent parameter in the path itself, but they are actually parameters. It's a bit inconsistent but that is a critic of the API and not Stripe.net.

**Comment by remi-stripe** [comment]
@clement911 Whether we usual a Nested Service or not is based on the URL associated with the API. For example, `Customer` is considered a "top-level resource" because its endpoint is `/v1/customers`, same for `Invoice` on `/v1/invoices`. On the other hand the `UsageRecord` class is a "nested resource" with a nested service because its URL path is `/v1/subscription_items/si_123/usage_records`. To create a `UsageRecord`, you need its "parent's id", here the `SubscriptionItem`'s id `si_123`.

Nested resources often make sense when one specific object creates and interacts with them. For example a `Person` is always associated with an `Account` and only that, same for `UsageRecord`.

Those can also cause issues in terms of designs and understanding though. For example `Refund` used to be nested under `Charge` via `/v1/charges/ch_123/refunds`. But what if you want to create a refund that is not linked to any charge? Those are often called "unliked refunds" in the industry. You could create a `UnlinkedRefund` resource but it would likely have the exact same details except not point to a `Charge`. So in that world, you wish you had chose `/v1/refunds` instead (which we moved to a few years ago).

Without going too deep into the weeds here, that is in part why a lot of resources are now top-level by default. We instead rely on naming and namespaces to organize the API better. And we try to only use nested resources when we know it is a better pattern.

All the resources you mentioned are top-level resources today and so they are not nested services.

As for the required versus optional for the `List` endpoint, it's just that we've defaulted to always making the parameter optional for that endpoint. While it's true that in the public API today they always require a parameters, it's not always true internally as we have more features that are not public, or are in beta. In this specific instance, it doesn't seem as important to encode whether one parameter is required or not in the method's prototype itself.

I hope all of this makes sense!

**Comment by clement911** [comment]
It does make sense.
Thank you for your explanations!

Here is a bit of feedback regarding the top level VS nested.
Personally I'm in favor of top level services as much as possible, for efficiency/performance reasons.

As an example, consider `CustomerBalanceTransaction`.
In our reporting app (which uses Connect), we want to keep a local copy of all of these transactions to generate quick reports without calling the API.

For the initial sync, we must load all of these transactions for the account (any time a new connected account is connected).
If it was a top level resource, we could simply paginate through the entire list (we would pass a null customer_id as the customer parameter)
But because it is a nested customer resource, we must query and paginate separately for every single customer! It's very slow, especially when you consider that most customers might only have a handful of transactions.

What's worse for `CustomerBalanceTransaction` specifically is that it doesn't generate any events (there is no `customer_balance_transaction.created` or `customer_balance_transaction.updated`).
So, in order to keep our local copy in sync, we have no choice but to poll periodically for every single customer.

Let me know if that makes sense too...

**Comment by clement911** [comment]
Feel free to close this issue as well.

**Comment by remi-stripe** [comment]
What you're saying makes sense for sure but in a way your application is quite unusual compared to 99.9% of Stripe integrations. Listing customer balance transactions without passing a `customer` is uncommon and is not something you'd ever build unless you're building an analytics application or some reconciliation job.

The API design here tries to cater to what the vast majority of integrations would need to understand the product, sometimes at a higher cost for adjacent integrations paths.

It's definitely not an easy decision. This is why `PaymentMethod` is top-level even though you'd never list those without a `Customer` today. There's a world in which you might want to run some direct analysis on all of your payment methods.

We're designing a new line item resource internally with the goal of making it canonical across all resources (Invoice, CreditNote, PaymentIntent, Checkout Session, etc.). And we've been having the debate between top-level and nested. The thing is that even if we did it top-level, we would likely require some "parent" id like we do on `PaymentMethod`. Because ingesting all line items without looking at which resource they are associated with is quite an uncommon pattern.

I'll flag this internally as we've been discussing this for a while and more data is always good :)

**Comment by clement911** [comment]
I guess I think of reporting and reconciliation as very common use cases.
Ok, maybe I'm a little bit biased given that our app does reporting 😋.
But it's not only those 2. Any sort of batch process could benefit from paging through all objects, and that is a much wider use case.

It seems to me that making the `customer` (or other parent resource id) optional instead of required would get the best of both worlds. Maybe I'm oversimplifying things.

**Comment by remi-stripe** [comment]
That's fair, I just don't think that's really true. For most people, listing all line items across every invoice and having them all mushed and mixed together would be a pretty confusing situation. Even if you can pass the invoice id and make it organized I disagree that it'd be the best pattern. Even for someone doing reconciliation, you'd start at the invoice first and for each one list its lines! But we'll keep this in mind for sure!

**Comment by clement911** [comment]
Ok, thanks for your comments.
