### ISSUE TITLE
ApplicationFeeRefund and IBalanceTransactionSource

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#2021]
I discovered something that seems pretty strange.

When a `BalanceTransaction` has a type of `'application_fee_refund'`, the source is expanded as the `application_fee` and NOT the `application_fee_refund`.

That seems quite un-intuitive at best.
I guess then there is no reason for `ApplicationFeeRefund` to implement `IBalanceTransactionSource`?

**Comment by remi-stripe** [comment]
@clement911 Yeah that is mostly historical and something we're hoping to clean up this year. We've done it a few times with other resources over the years. For example on API version [2015-08-19](https://stripe.com/docs/upgrades#2015-08-19) where the `source` on a BT for a `refund` and `dispute` became the `Refund` or the `Dispute` instead of the `Charge`.

I agree we likely should not implement that interface here and I likely got mixed up when I implemented it. I'm not sure it's worth the breaking change for now but I'll make sure to flag internally as we work on those improvements!
