### ISSUE TITLE
Creating tokens for Stripe Connect

### ISSUE THREAD

**Issue by VicenteCartas** [stripe/stripe-dotnet#203]
Hi,

In the documentation on how to charge a customer when using Stripe Connect (for a marketplace application), it says that you need to use a CustomerId and optionally a CardId:

https://stripe.com/docs/connect/shared-customers

It seems that the CardId parameter is missing from the StripeTokenCreateOptions (we have to pass the full credit card details).

Is there any way to pass a specific card to this method? Regards,

Vicente

**Comment by nhwilly** [comment]
I know this is closed, but sooner or later I need to address it.  

Stripe supports the concept of shared customers, and in order to charge on behalf of a connected account, we need to create a token for the customer/card stored on the platform account while including a reference to the connected account.  

That requires passing in a card id instead of a card and StripeTokenCreateOptions doesn't support that - it needs a card, which we won't have because we're repeatedly using the one from the platform account.  

The relevant documentation is [here](https://stripe.com/docs/connect/shared-customers}).

I really like this library and I'd be happy to contribute, but I am a total hack and I'm pretty sure I'd make a mess of it.  That said, if someone can point me in the correct direction, I'm happy to make a run at it.

**Comment by jaymedavis** [comment]
Awesome - just open a new issue (feel free to link to the code) and just copy your previous reply in there. A new issue would be better to not constantly alert everyone already on this previous issue. I don't think this work would be very hard or take long.
