### ISSUE TITLE
PriceUpdateOptions has PriceRecurringOptions but service not longer supports it on update.

### ISSUE THREAD

**Issue by Simonl9l** [stripe/stripe-dotnet#2084]
Library version 2020-03-02 

the .Net class `PriceUpdateOptions` has a `Recurring` member of type `PriceRecurringOptions`

However the [update price documentation](https://stripe.com/docs/api/prices/update) now indicated that this is now not an updatable property. 

```json
{
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameters: interval, interval_count",
    "param": "recurring[interval]",
    "type": "invalid_request_error"
  }
}
```

It would be great if the models aligned with the documentation and expected behavior.

**Comment by remi-stripe** [comment]
@Simonl9l That's because of the way sub-classes work in stripe-dotnet. We re-use the same class but some options are only available on Create. The reason it's on Update is that you _can_ update `trial_period_days` if you're using that feature. But changing a Price's interval or amount is not supported and that's why you are getting this error.

I hope this clears things up!

**Comment by Simonl9l** [comment]
Thanks - in that case I'd suggest the documentation be updated to add `recurring` into the Update Price Documentation with that caveat as the documentation is far from clear...

**Comment by remi-stripe** [comment]
We wouldn't be able to update the documentation since we don't actively document `trial_period_days`, it's here just for compatibility with the legacy `Plan` resource. So in the API reference `recurring` would not appear as a valid parameter, but stripe-dotnet and other client libraries do have to support this feature.

**Comment by Simonl9l** [comment]
So how is trial then supported with Product/Price?

**Comment by remi-stripe** [comment]
@Simonl9l We discourage from setting a trial period globally on the Price (or on the Plan). We have for almost 2 years now and new API versions ignore the plan's (or the price's) default trial period unless you explicitly pass `trial_from_plan: true`.

Instead, we recommend that you set the trial period in your code on Subscription creation or update via `trial_end` or `trial_period_days` as documented here https://stripe.com/docs/billing/subscriptions/trials
