### ISSUE TITLE
EphemeralKey class does not include "secret" field

### ISSUE THREAD

**Issue by createS0ftware** [stripe/stripe-dotnet#2105]
Hi 

Creating an EphemeralKey and returning it to a client app seems to be a problem with the SDK since the model object is missing the field "secret".

Should it have it ? I can't see how to get around it since the returned object is missing a vital key and value.

Is this intentional ? Do we need to update this object ?

**Comment by remi-stripe** [comment]
@createS0ftware Thanks for reaching out! This is intentional on our end yes. You should never have to access an Ephemeral Key's secret yourself. Instead, you are supposed to returned the exact raw JSON our API returns to the mobile SDK. The reason is that mobile SDKs are pinned to a different API version than stripe-dotnet and so it can't be safely deserialized this way. Just use `RawJson` property instead: https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/EphemeralKeys/EphemeralKey.cs#L43

**Comment by createS0ftware** [comment]
Thanks @remi-stripe , however, the Android SDK does not allow you to do that since the EphemeralKey class in the SDK does not contain that field and the the EphemerealJsonParser does not look for it (https://github.com/stripe/stripe-android/blob/master/stripe/src/main/java/com/stripe/android/model/parsers/EphemeralKeyJsonParser.kt)

So that's why it gives the error "No value for secret" 

How is one supposed to resolve that ? I can't extend any of the key classes that would make this happen unless i clone the whole project in my code.

**Comment by remi-stripe** [comment]
@createS0ftware I'm sorry but I don't really follow what you are describing. The code you mentioned is explicitly parsing the raw JSON, and the raw JSON that stripe-dotnet returns (which comes from the API) would have the secret in it as expected.

Is your code server-side in .NET explicitly returning the content of the `RawJson` property? Are you sure you are not incorrectly serializing the instance of `EphemeralKey` instead? That would not work, which is expected. We expect your server-side code to just return the raw string stored in `RawJson`.

I'd recommend following up with our support team if you need further help since it's more an integration question and you can share your code with them directly: https://support.stripe.com/contact

**Comment by createS0ftware** [comment]
I see it now, I don't know how i didn't see it before !
@remi-stripe  Thanks !

**Comment by createS0ftware** [comment]
I think i'll post this in the Android Sdk repository
