### ISSUE TITLE
Account capabilities changes causing issue

### ISSUE THREAD

**Issue by kAvItHa-cL** [stripe/stripe-dotnet#2183]
Using stripe v 15 . Not able to find property for setting mandatory capability which is changed recently in this version. Do I need to update to latest version forcefully or is there anyway to overcome is capabilities issue in this version itself.

**Comment by remi-stripe** [comment]
@kAvItHa-cL We would recommend upgrading to the latest version of stripe-dotnet in this case so that you can get all the recent API changes and features.

If you can't upgrade, you can use the `AddExtraParam` parameter to pass the extra information instead though it's not recommended. You could do
```
options.AddExtraParam("capabilities[card_payments][requested]", "true");
options.AddExtraParam("capabilities[transfers][requested]", "true");
```

Hope this helps!
