### ISSUE TITLE
Subscription.Plan and Subscription.Quantity removed?

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#2219]
These two properties were removed even though they are still documented.

**Comment by remi-stripe** [comment]
@clement911 `quantity` and `plan` on `Subscription` have been deprecated for multiple years now. As we support multiple plans (or rather Prices now) per Subscription, those top-level properties are confusing since they are only set if you have one SubscriptionItem.

We removed them from the client libraries in the latest major versions and also removed them from the API Reference for the Subscription resource [here](https://stripe.com/docs/api/subscriptions/object). You mentioned they are still documented but I don't see those anymore, can you clarify where you see them?

The properties are still _returned_ in the API since removing them would be a breaking change.

**Comment by clement911** [comment]
You're right, it's not in the docs anymore.
Closing.
