### ISSUE TITLE
Payment intent allow to set transfer description

### ISSUE THREAD

**Issue by vovikdrg** [stripe/stripe-dotnet#2229]
I am doing payment onBehalfOfCOnnected accounts and when connected account receive payments they dont see Description

```
  var options = new PaymentIntentCreateOptions()
            {
                Amount = (long) (orderView.GetTotalAmount() * 100),
                Currency = paymentReceiver.CurrencyCode.ToLower(),
                Metadata = new Dictionary<string, string> {{"OrderId", orderView.Id.ToString()}},
                TransferData = new PaymentIntentTransferDataOptions() {Destination = paymentReceiver.Destination},
                OnBehalfOf = paymentReceiver.Destination
}

```

I wish that PaymentIntentTransferDataOptions would have also ability to set description this will allow us to set description to be visible to connected account

**Comment by remi-stripe** [comment]
@vovikdrg Thanks for reaching out. Github issues should be limited to bugs or feature requests with the library itself. At the moment this is not something the API supports. It's also not something you should need since you can only use Destination Charges for Express and Custom accounts, where they don't have Dashboard access to see the description. You should never use this with Standard accounts as documented here https://stripe.com/docs/connect/charges

I'd recommend reaching out to our support team directly if you have follow up questions: https://support.stripe.com/contact
