### ISSUE TITLE
Business conditions (errors) as technical exceptions?

### ISSUE THREAD

**Issue by Thorium** [stripe/stripe-dotnet#2237]
This library seems to use StripeException (a technical error) as business case, which is an anti-pattern in software engineering.

.NET exceptions should not be used as business-flow.

For example:
- StripeException of "Your card does not support this type of purchase."
- StripeException of "Your card has expired."

Now, as modern day software is asynchronous, it easily gets wrapped inside System.AggregateException. Then your error-handling routines catch the exceptions and you start to search your business-cases from the exception flows, or you have to build the exception handling as part of your business logics. This is quite un-optimal.

**Comment by remi-stripe** [comment]
@Thorium Thanks for the feedback! Our API is currently designed around this approach where making requests can return an API error with the relevant HTTP status code (400 for a bad request, 402 for a decline, 429 for rate limits, etc.). The error API Resource is then mapped to an Exception in client libraries. This is not specific to stripe-dotnet and is true for all our libraries today. 

You do make a fair point, but undoing this would require re-designing the entire REST API which seems intractable in the medium (or even long) term I think.

I'll raise this internally to see whether people would design the API differently today if we started fresh!

I'm going to close this ask though since I can't see us changing this any time soon, I hope it's okay!
