### ISSUE TITLE
CustomerListOptions email is case sensitive and shouldn't be

### ISSUE THREAD

**Issue by luqman-hussain** [stripe/stripe-dotnet#2240]
The email address in the below is case-sensitive, therefore querying with the wrong case will not work. Case on email should not matter please fix this. 

var options = new CustomerListOptions
                {
                    Email= email
                };
                var service = new CustomerService();

**Comment by remi-stripe** [comment]
@luqman-hussain Sorry for the trouble but this is not something we will change. It would break any integration that relies on this for the multiple years the feature has been live.
We recommend that you normalize your email addresses from your customers instead so that if you want a case insensitive search you would ensure all emails are always lower-case.

I'd recommend reaching out to our support team directly to discuss this as it's more a feature request in the API and is not a bug with the stripe-dotnet library. You can contact them here: https://support.stripe.com/contact
