### ISSUE TITLE
Discrepancies between DateTime.Now and "now" value

### ISSUE THREAD

**Issue by hemmachat** [stripe/stripe-dotnet#2256]
Hi guys,

Our team found some discrepancies between .NET's DateTime.Now value and the string "now" value. For some cases, it was a few minutes different from the time we created the subscription schedule. It might be due to the processing queue in Stripe. I found that for creating a new subscription schedule, you recommend to use [SubscriptionScheduleStartDate](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/SubscriptionSchedules/SubscriptionScheduleStartDate.cs) for "StartDate" which is great. It solves our problem of the subscription timestamp. Now, we are trying to use the same "SubscriptionScheduleStartDate" value with "[Phase](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/SubscriptionSchedules/SubscriptionSchedulePhaseOptions.cs)" but the method signature is different as it does not take the value of "SubscriptionScheduleStartDate". As the change seems to be minimal but it might need to change all the "StartDate" method signatures across the whole code. So, is it possible to change the class to accept this "now" value? I can create a PR for these changes.

**Comment by remi-stripe** [comment]
@hemmachat When you pass the string `"now"` it's interpreted as the current time for Stripe. When you use `DateTime.Now` it's the current timestamp on your machine. If you see a few minutes difference it's likely due to clock skew and would indicate your server's clock is off. I'd recommend double checking the settings on your server and potentially enabling a sync with an NTP server.

For now, the `start_date` property inside the array of `phases` only expects a timestamp and it does not support the value `"now"`. It wouldn't make sense to support it since phases are sequential and you can't have all of them start `"now"`. What you can do is passe `start_date: "now"` top-level with the parameter you found. You don't have to pass `start_date` for each phase and they will just default to being sequential.

**Comment by hemmachat** [comment]
Thanks @remi-stripe, that make sense. Cheers.
