### ISSUE TITLE
How to get a list of team members for automated auditing

### ISSUE THREAD

**Issue by bilderbach** [stripe/stripe-dotnet#2265]
Feature Request:

Automating the process of finding any accounts that are tied to employees that have left the organization for audit and compliance purposes.

Looking for a way to access the list of stripe team members with your API.

Ideally would like to be able to disable these accounts right away as well with the API.

I think this would be a very useful feature and encourage customers to keep tighter security in your product as well as show your concern for security.

Thanks for looking at it!

**Comment by remi-stripe** [comment]
@bilderbach Thanks for the feedback. Github issues should be limited to bugs with the library itself so I'm going to close this out. I'd recommend flagging to our support team directly so that they can associate the request with your account. It's definitely feedback we heard before but we don't have plans to add an API for this just yet.

**Comment by bilderbach** [comment]
Sorry about that, the original template when creating a new request talks about a feature request so I thought this was the place...

**_

> Please only file issues here that you believe represent actual bugs or feature requests for the Stripe.net library.

_**

**Comment by remi-stripe** [comment]
@bilderbach We want feature requests about the library itself such as auto-pagination for example but not about the API itself. I definitely agree that it's a thin line and it's clearer for us than for users. The main reason we send you to support is to associate your feature request with your account so that we can reach out if we end up building this or starting a beta feature. But when you file requests here we also flag them internally so it's totally fine to default to this venue!
