### ISSUE TITLE
Charge.DestinationId vs Charge.TransferData.DestinationId

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#2268]
What is the difference between Charge.DestinationId vs Charge.TransferData.DestinationId?

I can't find Charge.DestinationId in the docs.

**Comment by remi-stripe** [comment]
The former is historical (but still supported). When we launched support for destination charges, you had to set `Destination` to the connected account's id and you also took your share via application fees. Only 2 years later did we add support for explicitly having `TransferData` to only transfer a portion of the funds instead of using application fees. We also added support for `OnBehalfOf` to explicitly decide if you settle the charge as the connected account or the platform.

We do recommend ignoring `Destination` and `DestinationId` though and relying on `OnBehalfOf` and `TransferData` moving forward.

**Comment by clement911** [comment]
Thanks for the quick response as usual
