### ISSUE TITLE
Apparent undocumented API change

### ISSUE THREAD

**Issue by TechnikEmpire** [stripe/stripe-dotnet#2280]
Sometime between December 16th and now, it appears that there was an undocumented API change. When fetching a stripe session, the `subscription` object used to be populated (I have checkout configured for subscriptions). It suddenly is not anymore.

I'm only reporting because I'm now afraid to launch using Stripe because the thought of having something like this explode my live site is a little terrifying.

**Comment by remi-stripe** [comment]
@TechnikEmpire Thanks for reaching out and sorry about the confusion. Stripe takes API versioning really seriously and we do aim to never make a breaking API change without first releasing a new API version for new users first.

The `subscription` property on the Checkout Session resource is always null when the Session is created. At that point, the customer has not attempted to pay yet and no Subscription has been created. Instead the Subscription is created while the customer attempts to pay on Checkout. Once they do, then the Session resource should have `subscription` properly set to the id `sub_123` of the created subscription.

I tested locally and was able to confirm this quickly on my account where `subscription` is null on creation and set after the Session completed both in the `checkout.session.completed` event but also in the API. I also looked at example requests from early December where I can also confirm that `subscription` was already null on creation at the time as expected.

It does not look like anything has changed recently and the behaviour mirrors what I would expect today. Would you be able to clarify if you're seeing otherwise? If so, do you have an example Session id (cs_test_123) where you are seeing the different behaviour?

**Comment by TechnikEmpire** [comment]
@remi-stripe Mid-December I finished Stripe integration in test mode. In that code (asp .net core 3.1) on checkout success endpoint I was always simply fetching the session from the CHECKOUT_SESSION_ID (populated by you guys) and then directly accessing `.Subscription.Id` without issue. I deployed to a new server yesterday and found out that the property is null and the docs seem to reflect this.

So either the test environment was lying to be during integration or someone was slipping me hallucinogens over a month long period that I was integrating lol

**Comment by TechnikEmpire** [comment]
I've just checked my git history and it looks like hallucinogens may be the answer. Sorry for the false alarm, I'm embarrassed.

**Comment by remi-stripe** [comment]
@TechnikEmpire On Checkout Session the property `subscription` is a string corresponding to the id of the underlying subscription if any (sub_123). That property can also be expanded into a full Subscription object as part of the [Expand feature](https://stripe.com/docs/expand).

What this means is that when you fetch the Session, by default you can access `.SubscriptionId` which contains the id of the Subscription but not `.Subscription.Id` as the property was not expanded and the Subscription object at that point is null. 
If you also expand the `subscription` property using `options.AddExpand("subscription");` for example then you will be able to access `.Subscription` as a full Subscription object and `.Subscription.Id` for example.

This behaviour hasn't changed recently. I also went and tested on a stripe-dotnet version that is from a few months ago (37.25.0 from August) and the behaviour was the same at the time. I also verified our test suite around expansion to make sure we didn't originally plan to set the internal id but the tests [here](https://github.com/stripe/stripe-dotnet/blob/master/src/StripeTests/Infrastructure/JsonConverters/ExpandableFieldConverterTest.cs#L12-L19) confirm as such.

I also see you updated the issue and confirmed this seems correct but I wanted to share what I investigated in case it helps you better understand how the library works around properties can be a string (id of the object) or an instance of the API resource being referenced!

**Comment by TechnikEmpire** [comment]
@remi-stripe thank you for the detailed information. For greater clarity, what happened was that after I had everything integrated and working, I thought I'd be super smart and guard my success return endpoints by fetching the actual session from you guys at that point and accessing the subscription to prevent spoofing. So like a true wizard, I just slapped the code in there at the end and patted myself on the back and didn't test it till yesterday. Yikes. 😅 

Again sorry about that and thank you for your response.

**Comment by remi-stripe** [comment]
No apology necessary, I'm glad we were able to figure it out and that your code is working now :)
