### ISSUE TITLE
Feature Request - Subscription Schedule Update accept metadata in Phase Items collection

### ISSUE THREAD

**Issue by Simonl9l** [stripe/stripe-dotnet#2293]
We use meta data to tie subscriptions items to specific products in our system. Subscription items support metadata (albeit don't show that information in the management portal - a sub feature request).

If we create a subscription directly we can add that Item [metadata](https://stripe.com/docs/api/subscription_schedules/update#update_subscription_schedule-phases-items) at time of creation; however once we use schedules, say, to cancel products from a subscription at the end of a period, we then, whilst the schedule is still active, have to use a schedule to add new products to the subscription to - and other similar scenarios until there is no longer an active schedule. 

The subscription schedule update does not support metadata in the Phase [Items](https://stripe.com/docs/api/subscription_schedules/update#update_subscription_schedule-phases-items).  This creates a functionality mismatch! 

The expectation is that once a phase become current/active, and the subscription items are updated, this meta data if supplied, would transpose to the underlying subscription item.

Our current work-around, since in our case they are unique per subscription, is to create the requisite price/product with the metadata and pass its ID in with as [item.price](https://stripe.com/docs/api/subscription_schedules/update#update_subscription_schedule-phases-items) and then transpose that into the subscription item in the processing of the requisite [customer.subscription.updated](https://stripe.com/docs/api/subscription_schedules/update#update_subscription_schedule-phases-items) web hook.

However this is kinda clunky and apparently more fragile and difficult to implement.

Additionally as above it would be great to be able to see subscription Item meta data in the management portal.

Another confusing aspect of the [documentation](https://stripe.com/docs/billing/subscriptions/subscription-schedules#updating) is that "_When updating a subscription schedule, you need to pass in **all** current and future phases that you want to keep._" If understood correctly one needs to  enumerate the current schedule and transpose everything into SubscriptionSchedulePhaseOptions and nested SubscriptionSchedulePhaseItemOptions, adding in and additional modifications. 

From a consistency perspective elsewhere, one would ordinarrilly just need to provide the deltas. In this case the unique marching identifier is the price. What is the correct approach? 

If its per documentation, this is tricky and fragile to implement.

**Comment by remi-stripe** [comment]
@Simonl9l Thanks a lot for the detailed feedback. Usually github issues are limited to bugs with the library itself (stripe-dotnet) and your feedback is more about the product API. While I will flag internally, I would still encourage you to send this feedback directly to our support team instead. Doing so will tie the feedback to your account and makes it easier to follow up if we end up modifying the API to support this. You can contact the support team here: https://support.stripe.com/contact

To answer the last question though you do have to pass all phases because there's no "id" that you can reference and it's all based on the order of phases. So if you wanted to add a phase, you can't just add the new price as the last phase, you need to pass the current and all future phases again on top of the new one. It's not a "merge" operation and is a "replace" instead. It definitely makes the schedules API a bit harder to work with today unfortunately and it's something we've been thinking about a lot recently but no firm plans for now.
