### ISSUE TITLE
'bank_transfer' as a funding_type in PaymentIntentCreateOptions

### ISSUE THREAD

**Issue by larslinq** [stripe/stripe-dotnet#2294]
Please add 'bank_transfer' as a funding_type to the PaymentIntentCreateOptions object like

payment_method_options: {
    customer_balance: {
      funding_type: 'bank_transfer',
      bank_transfer: {
        types: ['sort_code'],
      },
    },

its in PaymentIntentPaymentMethodOptionsOptions

Also display_bank_transfer_instructions need to be added to PaymentIntentNextAction class

https://stripe.com/docs/payments/bank-transfers/accept-a-payment

thanks

**Comment by remi-stripe** [comment]
@larslinq Thanks for reaching out! The feature you are using is in private beta and is not public today which is why it's not supported in client libraries like stripe-dotnet. The feature will be supported in the future once it ships publicly, but until then it can't be added. If it were and we had to make breaking changes during the beta we could break all existing users.

Unfortunately this means you can't use it directly with stripe-dotnet and will have to make your own raw POST requests for it to work. While we support passing undocumented parameters via `AddExtraParams`, this beta feature requires a custom beta flag in the API version header which the library does not support.

For now, I'm going to close this out as it's not a limitation with the library itself, it's just that betas like this one can't be supported in this library for now. Once the feature ships publicly, stripe-dotnet will immediately support it.

**Comment by larslinq** [comment]
Thanks

Yes I understand its beta and you don’t have a beta version of the SDK available.

I just wonder how is it possible to betatest this feature if its not implemented in the sdk?

The problem is that we have been promised this functionality and was told that we can use it now!?
We need this to be able to launch.

I know we could use raw post requests but there is a reason for using SDKs
And a bit waste of time if its gonna be released soon

That’s why my original question was:
When will this be implemented?

Are there other parts missing in the SDK that could hold us back?

Connected Accounts?
Terminals?

Further on:

“If it were and we had to make breaking changes during the beta we could break all existing users.”
I don’t see why this feature is different from any other changes to the SDK. How would that impose breaking changes?

I see its implemented in the other SDKs!
Why is that then?

“this beta feature requires a custom beta flag in the API version header which the library does not support.”
Why don’t you add this then?

Thanks again

Lars

**Comment by remi-stripe** [comment]
@larslinq Every feature that is public and live is supported in all our client libraries. We just do not support beta features today in libraries for statically typed languages. At the moment, this means you either can't use the beta until it ships publicly or that you do have to make your raw API requests yourself. It's something we want to fix in the future for sure but it's a matter of priorities and right now shipping beta versions of stripe-dotnet is not something that we are able to do.

I do understand it's blocking you but this is a public issue on stripe-dotnet and we don't discuss private betas or secret features publicly. It's unfortunately not possible to use this beta with stripe-dotnet for now.
