### ISSUE TITLE
How to get ClientId

### ISSUE THREAD

**Issue by GlebGulin** [stripe/stripe-dotnet#2296]
Good day. I use stripe in .NET Core. In appsettings.json I set PublishableKey and SecretKey. During debug, I got ClientId = null, but I need it to use for OAuth. For what reasons this can happen and how is it possible to get the ClientId. Thank you so much

**Comment by remi-stripe** [comment]
@GlebGulin Github issues should be limited to bugs and feature requests with the stripe-dotnet library itself. We don't really have a default JSON configuration for the library and you code so the `appsettings.json` file you mention must come from your own code or the example docs you followed to set this up. If `ClientId` is null it's likely because your code isn't properly reading from that file. You can find your client application's id directly in the Dashboard in your Connect settings here: https://dashboard.stripe.com/settings/applications

If you have any follow up questions I'd recommend reaching out to our support team instead: https://support.stripe.com/contact
