### ISSUE TITLE
Bug with new Newtonsoft.Json 13.0.1 - 'Stripe.StripeConfiguration' threw an exception

### ISSUE THREAD

**Issue by franzil** [stripe/stripe-dotnet#2298]
OS version: various (Windows Server 2012 - Windows Server 2016 - Windows 10)
.NET version: 4.8
Stripe.net library: 39.40.0

Upgrading Newtonsoft.Json to 13.0.1 broke the StripeConfiguration.ApiKey initialization

```
Exception:
Type: System.TypeInitializationException
Message: The type initializer for 'Stripe.StripeConfiguration' threw an exception.
StackTrace:
at Stripe.StripeConfiguration.set_ApiKey(String value)
... <omitted> ... Helper.vb:line 280

280. StripeConfiguration.ApiKey = StripeLiveSecretKey
```

Reverted Newtonsoft.Json to 12.0.3 - everything works correctly

**Comment by remi-stripe** [comment]
@franzil Thank you for the heads up. It's likely there was a major change in that 13.0.0 version that isn't compatible with stripe-dotnet. We'll have a look to see if we can patch this and otherwise document that we only support up to 12.X.

**Comment by samson2511** [comment]
I am trying to use NewtonSoft.Json version 10.0.0. When I created my ASP.NET project (name->StripeIntegration) and added NuGet package for Stripe. Since my actual website is using Newtonsoft version 10.0.0, I referenced that in StripeIntegration, which worked fine.
But when I moved the files (dlls and aspx), I get the error - The type Initializer for Stripe.StripeConfiguration threw an error. 
The same Stripe code that works in a standalone ASP.NET project doesn't work when the project files are moved to another ASP.NET project
Am I missing any entries in config files or something?
Thanks in advance.

**Comment by azulo-dev** [comment]
I was running into the same issue, but only on my docker image, the issue was when i ran `dotnet publish` it would include an early version of newtonsoft (v9.0) and this was due to a test project in my solution that was being built along side it.

Run `RUN dotnet publish -c Release -o out` and check the version of the newtonsoft dll in the 'out' folder and ensure its the correct version.

I found the fix in this [Stackoverflow post for something similar](https://stackoverflow.com/a/69434859/992936)

I resolved it with updating the test project to have `<IsPublishable>false</IsPublishable>`:

```
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>


```

**Comment by pakrym-stripe** [comment]
Hi, it seems there are multiple separate issues in this thread. Most of which seem to be publishin-related. If you still experiencing this or similar error comment with the target framework you are using, versions of `Stripe.NET`, `Newtonsoft.Json` and the full stack trace of the error.

**Comment by pakrym-stripe** [comment]
Closing as we haven't heard about new occurrences in a while. If you still experience this issue please reopen and add details about your environment.

**Comment by AnandAsirA** [comment]
Is there any fix for the issue mentioned?

**Comment by pakrym-stripe** [comment]
@AnandAsirA, do you experience this issue? Can you, please provide the version of .NET, Stripe.NET and Newtonsoft.Json you are using and the exception details you are seeing.

**Comment by AnandAsirA** [comment]
We were using .NET 4.7, Stripe.net version "39.80.0", 
As part of the CMS upgrade, we changed the target Framework to .Net 4.8 and Newtonsoft.Json version 13.0.1 and stripe stopped working. We are not able to do any stripe functionality. We tried upgrading the "Stripe.net" version "40.7.0" But isn't working for us.

**Comment by AnandAsirA** [comment]
Any updates? Also any release on .NET 6 nuget release?

**Comment by pakrym-stripe** [comment]
@AnandAsirA, can you share the error you are seeing? 
Can you check your web.config and confirm you have bindingRedirect entry to Newtonsoft.json?

Stripe.net already supports .NET 6.
