### ISSUE TITLE
Default Azure Function v3 template doesn't work

### ISSUE THREAD

**Issue by github-acedom** [stripe/stripe-dotnet#2304]
Logged a support ticket but didnt really go anywhere.

Having an issue using the Stripe.Net package for a Webhook, steps to reproduce:

- Create a new Visual Studio 2019 project based on template Azure Function v3
- Choose Http Trigger

**Function works when it gets a POST**

- Add Stripe.Net (39.43.0) and something from the library

```
using Stripe;
using System;

var secret = Environment.GetEnvironmentVariable("StripeSecret");
string json = await new StreamReader(req.Body).ReadToEndAsync();
var @stripeEvent = EventUtility.ConstructEvent(json, req.Headers["Stripe-Signature"], secret);

```
**Function no longer works**

```
[2021-04-11T02:28:13.328Z] Host lock lease acquired by instance ID '0000000000000000000000003F1A282D'.
[2021-04-11T02:28:14.628Z] Executing 'StripeWebhook' (Reason='This function was programmatically called via the host APIs.', Id=f647a9d4-c3b9-4c0b-a811-4dc54fbea578)
[2021-04-11T02:28:14.676Z] C# HTTP trigger function processed a request.
[2021-04-11T02:28:14.818Z] Executed 'StripeWebhook' (Failed, Id=f647a9d4-c3b9-4c0b-a811-4dc54fbea578, Duration=213ms)
[2021-04-11T02:28:14.819Z] System.Private.CoreLib: Exception while executing function: StripeWebhook. System.Private.CoreLib: String reference not set to an instance of a String. (Parameter 's').
```

![image](https://user-images.githubusercontent.com/64336712/114290265-b589ba80-9ac1-11eb-9f07-3a4aee660beb.png)

What am I missing here?

**Comment by remi-stripe** [comment]
@github-acedom There isn't much in the screenshot to help debug here unfortunately. This doesn't look like an issue with stripe-dotnet at first and more an issue with your code especially as the code doesn't log anything to indicate what the issue could be nor catch any errors that can be raised by the library.
My recommendation here is to cleanly log at each step to a file for example so that you can better understand which line is crashing if any. Also make sure to wrap all Stripe calls in a catch as documented in https://stripe.com/docs/api/errors/handling?lang=dotnet

**Comment by github-acedom** [comment]
Sorry for the noise, I was having an issue with the function firing which was a package conflict related problem.  In my attempt to troubleshoot that I had overlooked that issue was resolved and it was a different issue now.

Anyway, for completeness this issue was because StripeSecret was not defined.

Please close the issue - thanks

**Comment by remi-stripe** [comment]
Glad to hear you figured this one out and that it's not a problem with the library itself. Thanks for updating us back :)
