### ISSUE TITLE
Checkout Session - Add 'single_use' param for SessionSetupIntentDataOptions

### ISSUE THREAD

**Issue by lwardzala** [stripe/stripe-dotnet#2305]
Hello,
I noticed that **SetupIntentCreateOptions** already contains the _'single_use'_ parameter (that is very useful by the way) for restricting mandates to exact amount.
However it's not possible to pass the parameter when I want to use Stripe Checkout (**Stripe.Checkout.SessionSetupIntentDataOptions**).
As I can see it's more than updating Stripe.net library because the API doesn't accept the parameter in this context as well. (I hoped that it's at least possible to pass that as an extra param).

I'm looking forward to any possibility to use the feature within Stripe Checkout.

**Comment by remi-stripe** [comment]
@lwardzala This is not something our API supports for Checkout today and I don't think we'd add this to the API as Checkout only supports a subset of the feature, focusing on common flows. Since github issues are limited to bugs with the library itself I'm going to close this out. I'd recommend reaching out to our support team instead for surface your exact use-case and clarifying why you need this feature and they should be able to help escalate internally. You can contact them here: https://support.stripe.com/contact
