### ISSUE TITLE
Stripe Connect AccountService uses DateTime in AccountTosAcceptanceOptions but API requires Integers in Seconds

### ISSUE THREAD

**Issue by arjvintech** [stripe/stripe-dotnet#2332]
Greetings! We have been using version 39.50.0 of the stripe.net library. Code that has been working successfully up to now (code specific to the Stripe Connect API) is now failing for the same library version (and same API version -- 2020-08-27). The error that we are now getting is: 

`ToS acceptance date is not valid. Dates are expected to be integers, measured in seconds, not in the future, and after 2009.`

This happens when calling the Create() method in the AccountService.  The AccountTosAcceptanceOptions only accepts a nullable DateTime for the Date (no way to set Unix Time). We tried upgrading to the latest version of the library (39.54.0) -- but the issue persists.  

Again, this code has been working for some time (up to early last week, at least) -- but is now failing. Thanks for the great work on the library.

**Comment by remi-stripe** [comment]
@arjvintech The library will convert a `DateTime` to a unix timestamp automatically for you. The issue seems to be with the value you are passing and not with the library. The most common issue is to have your server's clock incorrectly set in the future for example so when you try to indicate the ToS was signed "now" the date you passed is rejected by our server because it's in the future.

I'd recommend looking at the request logs in the Dashboard to confirm the exact timestamp you're passing in the API.

**Comment by arjvintech** [comment]
Thank you so much @remi-stripe. Our codebase did not change -- but server time did. (Sigh). Sorry to bother you and the team with this issue. I will close it out. Thank you so much for your response and for you/the team's effort in working to build and maintain this library.

**Comment by remi-stripe** [comment]
No bother at all! This can be tricky to debug on your own since everything you do seem correct at first read. It's just common enough for developers to hit this that I know this is a good first step! I'm glad you got unblocked :)
