### ISSUE TITLE
PaymentIntent NextAction object not being assigned correctly when type is use_stripe_sdk

### ISSUE THREAD

**Issue by marcodafonseca** [stripe/stripe-dotnet#2361]
During the Subscription process, a PaymentIntent might require authentication and come back with the following data shape:

```
{
    "next_action": {
        "type": "use_stripe_sdk",
        "use_stripe_sdk": {
            "type": "three_d_secure_redirect",
            "stripe_js": "https://example-url.com",
            "source": "src_SourceID"
        }
    }
}
```
However, the SDK doesn't support the `use_stripe_sdk` property and therefore we are forced to use the JObject to the get the `stripe_js` property that holds the authentication URL in it. Considering the rest of the objects are strongly typed it is a bit frustrating to suddenly leave convention behind for this particular scenario.

Currently I'm getting the URL as follows:

```
value.RawJObject["next_action"]?["use_stripe_sdk"]?["stripe_js"]?.ToString()
```

Can this please be amended soon as it shouldn't be a big issue to resolve? I will try issue a pull request myself soon if that will help speed things up.

OS Version: Windows 10 - Windows Feature Experience Pack 120.2212.3530.0
.NET Version: 5.0
Stripe.net Version: 39.63.0

Thanks in advance. The rest of the SDK has been super helpful!

**Comment by remi-stripe** [comment]
@marcodafonseca The `use_stripe_sdk` hash is considered fully opaque and should never be used by any integration. It's purely "internal" so that our client SDKs (Stripe.js or Mobile SDKs) can parse this information and to the right next steps. The shape of this hash can change at any point and we wouldn't consider this a breaking change. That's why it has not been added to stripe-dotnet or any of our other client libraries. 

If you do not want to use Stripe.js or equivalent and still want to handle 3DS yourself, you should be passing `use_stripe_sdk: false` so that we return `redirect_to_url` instead.

Does that make sense?

**Comment by marcodafonseca** [comment]
Oh, is that what I was doing wrong?

That worked perfectly. Thank you so much :)

**Comment by remi-stripe** [comment]
Sorry, the `use_stripe_sdk` parameter is pretty obscure on purpose as it's really uncommon for integrations to try and do everything from scratch versus letting our client-side libraries/SDKs do all the work for you! I'm glad you're unblocked though :)

**Comment by marcodafonseca** [comment]
Haha, no worries. It's my fault. This is my first time working with Stripe
and we had already completed all our frontend elements before tackling the
integration so I wasn't aware of your frontend libraries until it was too
late :P

Em sex, 20 de ago de 2021 23:37, remi-stripe ***@***.***>
escreveu:
