### ISSUE TITLE
Card Present Payment Method missing properties

### ISSUE THREAD

**Issue by natehitze** [stripe/stripe-dotnet#2362]
This class: https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/PaymentMethods/PaymentMethodCardPresent.cs

Not much else to add other than it would be nice to have access to the properties like `PaymentMethodCard`.

**Comment by remi-stripe** [comment]
@natehitze The stripe-dotnet has the properties that are exposed in the API. Today, there are no properties exposed on the `PaymentMethod` object for `card_present` which is confirmed by the [public docs](https://stripe.com/docs/api/payment_methods/object#payment_method_object-card_present). 

We don't surface anything there because the PaymentMethod doesn't get attached to a customer and doesn't get re-used. It's only for a given payment. The resulting `Charge` object will surface all relevant information about that specific card present transaction in `payment_method_details[card_present]` as documented [here](https://stripe.com/docs/api/charges/object#charge_object-payment_method_details-card_present).

Hope this helps!
