### ISSUE TITLE
Payment intend abandon deprecated error.

### ISSUE THREAD

**Issue by GusBeare** [stripe/stripe-dotnet#2429]
I didn't want to post this here but I'm not getting an explanation from Stripe support. Just passed onto someone else who is "looking into it".

Up until recently I was able to set a checkout payment intent to "abandoned". With the following code in Test Mode.

    var service = new PaymentIntentService();
    var o = new PaymentIntentCancelOptions();
    o.CancellationReason = "abandoned";
    await service.CancelAsync(booking.StripePaymentIntentId, o);

But I suddenly started to get this error:

**"You cannot perform this action on PaymentIntents created by Checkout. (Hint: The feature you are trying to use is deprecated.)"**

I am still waiting for a reasonable answer from Stripe support. I cannot find any reference to this in the Change log or documentation. Nowhere does it say that this is deprecated.

I have worked around this issue by expiring the session instead with:

                var s = new SessionService();
                await s.ExpireAsync(booking.StripeCheckoutSessionId);

But I am alarmed by this error because I nearly went live before spotting it. Luckily I checked my logs and found it.

Can anyone shed any light?

thanks
Angus

**Comment by paulasjes-stripe** [comment]
Cancelling the underlying PaymentIntent used to be a workaround for expiring Checkout Sessions before that functionality was readily available. Now you can expire a Checkout session directly via this endpoint: https://stripe.com/docs/api/checkout/sessions/expire?lang=dotnet

Since directly changing the underlying PaymentIntent is a deprecated feature, you're getting that error. Using the new endpoint should fix this for you. Bear in mind you'll need to be on at least version [39.77.0](https://github.com/stripe/stripe-dotnet/releases/tag/v39.77.0) of stripe-dotnet to use that functionality.

**Comment by GusBeare** [comment]
Thanks @paulasjes-stripe. As you can see in my post I am now using the expire session endpoint. So problem solved.

BUT, the problem is that the Stripe documentation does not say anything that I can see about this feature being now deprecated.

https://stripe.com/docs/api/payment_intents/cancel

If there had been a red flag and a pointer to using session expiration I would not have wasted time on this.

Thanks

**Comment by GusBeare** [comment]
There is also nothing in the change log about when this deprecation happened. Am I missing something?

**Comment by remi-stripe** [comment]
@GusBeare Only a handful of developers ever used that flow so we reached out to affected integrations privately before changing the behaviour. In that case, we don't document the change itself since we make sure all affected integrations are aware.

Unfortunately, it looks like we only reached out to integrations doing this in Live mode and not the ones that did this only in Test mode, which seems to be your case. I'm sorry for the confusion and the time lost here, this is definitely something we could approach better. We're going to see if we can improve the docs to make that more obvious and also check other integrations that hit this error in Test mode recently.

**Comment by GusBeare** [comment]
Hi again.  Just so you know. It's been nearly two weeks now and Stripe docs still don't refer to this feature as *deprecated*.
It's not really fair on new developers not to update the documentation is it?  It's a two minute fix.

https://stripe.com/docs/api/payment_intents/cancel

**Comment by GusBeare** [comment]
ps: In my humble opinion it's also not great to close an issue until it's actually been addressed and not commented on.

**Comment by remi-stripe** [comment]
@GusBeare Github issues are limited to bugs with the stripe-dotnet library. This isn't a bug with the library, it's a docs improvement request. We have it on our list to improve but it's still a really rare error that almost no one would experience so it hasn't made it to the top of the priority list yet. We haven't forgotten though and we'll try to do it this week.

**Comment by remi-stripe** [comment]
We made some changes to our public documentation for the [Cancel PaymentIntent API](https://stripe.com/docs/api/payment_intents/cancel) to explicitly mention you can't cancel a PaymentIntent associated with Checkout.
