### ISSUE TITLE
customer_details is not available on SessionCreateOptions

### ISSUE THREAD

**Issue by jacksonsoft** [stripe/stripe-dotnet#2481]
### Describe the bug

When generating a single payment using SessionCreateOptions you should be able to set the customer_details node on the checkout_session object as per https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-customer_details
This should enable populating the card name and address from known details as is best practice, wather than requesting them again.
Note that generating a customer and passing in the customerId to the SessionCreateOptions only populates the email address.

### To Reproduce

Create new SessionCreateOptions

### Expected behavior

Should be possible to set customerdetails at the indicated code point.

### Code snippets

```csharp
var sessionOptions = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        PriceData = new SessionLineItemPriceDataOptions
                        {
                            Currency = "GBP",
                            UnitAmount = (long)Math.Floor(amount * 100),
                            ProductData = new SessionLineItemPriceDataProductDataOptions
                            {
                                Name = description
                            }
                        },
                        Quantity = 1
                    },
                },
                Mode = "payment",
                CustomerEmail = email
              // should be able to set customerdetails here  
            };
            var sessionService = new SessionService();
            Session session = sessionService.Create(sessionOptions);
```

### OS

Windows

### .NET version

.Net Framework 4.8

### Library version

stripe-dotnet v39.110.0

### API version

2022-05-05

**Comment by remi-stripe** [comment]
@jacksonsoft the `customer_details` is a **property** on the `Session` resource. It's something that we (Stripe) set after the Session is completed to reflect information about the customer. This is what the [documentation](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-customer_details) you linked to represents and maps to what is built on the `Session` class in stripe-dotnet [here](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/Checkout/Sessions/Session.cs#L160-L161).

If you look at the Create Checkout Session API [documentation](https://stripe.com/docs/api/checkout/sessions/create) there is no `customer_details` parameter. This doesn't exist today and that's why it's not in the stripe-dotnet library.

Overall, there is no bug here in the library. You might want this as a feature request, in which case you can report this to our support team [here](https://support.stripe.com/contact). I'm confident that's not something we would add since you can already pre-fill the Customer id `cus_123` or their email and we already load their most recently used payment method if they have used one on Checkout before.

I'm going to close this out but don't hesitate to talk to our support team if you have any follow up questions, they'd be happy to help.
