### ISSUE TITLE
Invalid IP Address error on production server

### ISSUE THREAD

**Issue by FoxwoodDesign2017** [stripe/stripe-dotnet#2688]
### Describe the bug

I am updating Stripe Connect accounts via the API. Everything works perfectly on localhost.

As soon as try it on the live server, every API request is returning a 500 error, Invalid IP address.

I am still working in Test Mode on stripe, as we are still in development, so I am using the same API Keys.

The website is hosted on Azure App Services (windows) - with the same setup as my localhost.

Please can you suggest how I can resolve this so we can resume testing on our live servers.

Many thanks

### To Reproduce

I dont know, because I don't know what's causing the issue

### Expected behavior

Return success rather than Invalid IP Address

### OS

Windows

### .NET version

Dot Net 6

### Library version

Stripe DOT NET 41.7.0

### API version

Not sure

**Comment by richardm-stripe** [comment]
Hello @FoxwoodDesign2017. This forum is for bug reports and feature requests for the stripe-dotnet library. It sounds like you need help with your environment or with your integration, and should contact Stripe Support through [support.stripe.com/contact](support.stripe.com/contact) because they can help you more interactively -- or Azure support, since it seems likely that the problem resides there.
