### ISSUE TITLE
SetupIntentPaymentMethodOptions missing Alipay

### ISSUE THREAD

**Issue by GonzaloHierro** [stripe/stripe-dotnet#2722]
### Describe the bug

We are developing the subscription for Alipay payment method however it is not eligible in the libraries. Both payment method and currency are required for the development but missing on the libraries

### To Reproduce

Alipay payment method should be added, it shows already on Stripe documentation but not on SDK. 

![stripe alipay](https://github.com/stripe/stripe-dotnet/assets/138202961/3d6e9e7d-dc2f-4b46-8f93-9ad70d2c2c54)

https://stripe.com/docs/api/setup_intents/create?lang=dotnet

### Expected behavior

We expect the method to be added to the library like the others:

![MicrosoftTeams-image (13)](https://github.com/stripe/stripe-dotnet/assets/138202961/d338d988-30c8-46f4-a74b-35665b6a729c)

### OS

Windows

### .NET version

.net framework 4.6

### Library version

stripe-dotnet version 40.0.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
Hey @GonzaloHierro, in your picture you can see it says `Preview feature` next to this. This is a beta feature that is not public right now which is why it's not in the library at the moment. In the future, when the feature gets released to everyone, it will be added to the library automatically.
In the meantime you can use the option documented [here](https://github.com/stripe/stripe-dotnet#how-to-use-undocumented-parameters-and-properties) to set those parameters.

If you have follow up questions, we recommend working with our support team instead as you're using a beta feature that isn't publicly available. You can contact them here: https://support.stripe.com/contact

**Comment by GonzaloHierro** [comment]
Ok, thanks a lot for the workaround, we'll try that. 

We asked via github cos the Stripe support team told us to. We passed 2 approval processes to use Stripe for Alipay subscriptions even though this was a beta feature.. we really hope it gets released globally soon.
