### ISSUE TITLE
Specifying Currency in PriceListOptions not work

### ISSUE THREAD

**Issue by carbonete** [stripe/stripe-dotnet#2745]
### Describe the bug

We have prices in USD and BRL, when trying retrieve specifying Currency  = "brl", always return prices in usd.

### To Reproduce

1 . Create PriceListOptions with Currency ="brl"
2. create PriceService
3. List price. Always return in USD.

### Expected behavior

return active prices in BRL. But return USD prices.

### Code snippets

```csharp
PriceListOptions options = new PriceListOptions { Active = true, Currency = "brl" };
PriceService service = new PriceService();
StripeList<Price> prices = await service.ListAsync(options);
```

### OS

windows 10

### .NET version

.Net Standard 2.0

### Library version

Stripe.net 41.18.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@carbonete Github issues should be limited to bugs with the library itself and in this case your question is more related to confusion about how the API works. This is more akin to integration support and I'd recommend working with our support team directly for help instead: https://support.stripe.com/contact

To clarify things here, what's likely happening is that you have "multi-currency" Prices where you defined Prices in USD but with `currency_options` ([doc](https://stripe.com/docs/api/prices/create#create_price-currency_options)) for other currencies. In that case the Price's default currency is USD but it does support BRL which is why it gets returned. If you change your code to properly include `currency_options` in the Price using the [Expand feature](https://stripe.com/docs/expand#includable-properties) you can quickly confirm that the returned Prices each have a BRL option.

Your code would look like this:
```
PriceListOptions options = new PriceListOptions {
  Active = true,
  Currency = "brl",
  Expand = new List<string> {
    "data.currency_options",
  },
};
PriceService service = new PriceService();
StripeList<Price> prices = await service.ListAsync(options);
```

If you do that code and then print the result you can see that the Prices returned will have an entry inside `currency_options` for BRL.

If you do have any follow up questions though please make sure to talk to our support team instead as our API works as expected in this case.
