### ISSUE TITLE
Charge.DisputeId field removed

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#2766]
### Describe the bug

We upgraded to the latest SDK but Charge.DisputeId was removed.
Is this API change documented anywhere? What is the alternative to get the dispute id?

### To Reproduce

Look at the Charge object and notice that the DisputeId property doesn't exist anymore

### Expected behavior

not sure

### OS

n/a

### .NET version

n/a

### Library version

42.4.0

### API version

2023-08-16

**Comment by remi-stripe** [comment]
@clement911 Sorry for the confusion on that one. The `dispute` property in the API has been deprecated and undocumented for a long time now (at least a few years) but was still incorrectly in the SDKs. We cleaned this up with the latest major which was already doing some substantial clean up across all languages.

The reason for the deprecation is that, while rare, one Charge can have multiple separate Disputes in the API. Having just one id wouldn't work anymore which is why we deprecated it a while ago. It's something we should definitely have surfaced more clearly in the SDK over the years but unfortunately missed that one.

You should use the List Disputes [API](https://stripe.com/docs/api/disputes/list) instead to get the Dispute(s) associated with that Charge or PaymentIntent id.
