### ISSUE TITLE
Cannot create card token on server side code (exception thrown "Sending credit card numbers directly to the Stripe API is generally unsafe")

### ISSUE THREAD

**Issue by vhj1995** [stripe/stripe-dotnet#2816]
### Describe the bug

We are trying to add card payment method but could not do it.

Code throws following error:

![image](https://github.com/stripe/stripe-dotnet/assets/25062869/9f22aab9-6437-47b0-864f-3de12c602170)

"Sending credit card numbers directly to the Stripe API is generally unsafe" 

As of now we have put effort to build many applications which uses server side payment processing. We need a way to tokenize card on server side.

Can anyone guide us on this?

### To Reproduce

https://stripe.com/docs/api/tokens/create_card?shell=true&api=true&resource=tokens&action=create

Browse above link, run the code in terminal.

### Expected behavior

![error](https://github.com/stripe/stripe-dotnet/assets/25062869/b50300a5-a67a-4ec7-b934-03a12c852615)

### Code snippets

```csharp
var tokenOptions = new TokenCreateOptions
                    {
                        Card = new TokenCardOptions
                        {
                            Number = model.CardNumber,
                            ExpMonth = Convert.ToString(expireMonth),
                            ExpYear = Convert.ToString(expireYear),
                            Cvc = Convert.ToString(model.SecurityCode),
                            Name = model.NameOnCard,
                            AddressCity = model.Address1,
                            AddressCountry = model.Address2
                        }
                    };

                    var tokenService = new TokenService();
                    Token stripeToken = tokenService.Create(tokenOptions);
                    string tokenId = stripeToken.Id;
```

### OS

Windows

### .NET version

6.0

### Library version

Latest

### API version

Latest

**Comment by remi-stripe** [comment]
@vhj1995 Github issues are limited to bugs with the stripe-dotnet SDK itself. Your question is an integration support one better directed to our support team: https://support.stripe.com/contact
The API error message is also quite descriptive and tells you exactly what the error is and why and links to a support article with even more information: https://support.stripe.com/questions/enabling-access-to-raw-card-data-apis

You should not send raw card details server-side and instead collect those client-side with [Elements](https://stripe.com/docs/stripe-js#elements). Otherwise you should follow the steps in the article mentioned above (and in the error message).
