### ISSUE TITLE
Subscription: Invoice Settingsd Custom Fields

### ISSUE THREAD

**Issue by illexx** [stripe/stripe-dotnet#2845]
### Is your feature request related to a problem? Please describe.

Via Stripe dashboard, there is the possibility to add invoice custom fields (key-value-pair), which will appear on every invoice according to the subscription.

This option is a super useful way to help customers with multiple active subscriptions to track and assign invoices.

This described options is missing in stripe.net nuget package.

### Describe the solution you'd like

The Stripe dashboard is capable to send invoice custom fields attached to a subscription.
It works using the API call: 

[POST] ../v1/subscriptions/sub_xxx:
{
	"invoice_settings[custom_fields][0][name]": "CustomFieldKey1",
	"invoice_settings[custom_fields][0][value]": "CustomFieldValue1",
	"enable_incomplete_payments": "false",
	"off_session": "true"
}

I ask you to add this properties to Stripe.SubscriptionInvoiceSettingsOptions in the stripe.net nuget package.

**Comment by remi-stripe** [comment]
@illexx Github issues are limited to bugs or feature requests with the SDK itself. The SDK doesn't support this because the API doesn't today, it's only in the Dashboard. Since this is a feature request for the API, you can flag your interest to our support team who will track your feature request: https://support.stripe.com/contact
