### ISSUE TITLE
v44.8.0 charge.BalanceTransactionId is null or empty

### ISSUE THREAD

**Issue by leodip** [stripe/stripe-dotnet#2914]
### Describe the bug

After upgrading from `43.23.0` to `44.8.0` I noticed that this call:

`var charge = await chargeService.GetAsync(latestChargeId);`

...  is returning a `charge` instance without a `BalanceTransactionId` string attached.

This problem appears to be intermittent. Sometimes it works, sometimes it doesn't, without me changing anything on the code.

Are you aware of any issue related to BalanceTransactionId in v44.8.0?

Out stripe API version is **2018-02-28**.

### To Reproduce

`var charge = await chargeService.GetAsync(latestChargeId);`

### Expected behavior

To always receive a charge with a BalanceTransactionId.

### OS

Windows and Linux

### .NET version

.NET 8

### Library version

v44.8.0

### API version

2018-02-28

**Comment by remi-stripe** [comment]
@leodip This is expected behaviour. When you upgraded, you changed the major version which includes breaking changes. This is covered in the changelog if you look at the 40.0.0 release notes [here](https://github.com/stripe/stripe-dotnet/blob/master/CHANGELOG.md#4400---2024-04-10).

That major version SDK is pinned to the latest of the API [2024-04-10](https://docs.stripe.com/upgrades#2024-04-10) which changed the default behaviour for PaymentIntent where the funds are captured asynchronously to improve the overall latency of the API. You can read more about this in [this guide](https://docs.stripe.com/payments/payment-intents/asynchronous-capture). So the BalanceTransaction property on Charge will be null on creation and will be set asynchronously after. Your code can listen to the `charge.updated` Event to know when the funds are being moved into your balance and see the `BalanceTransaction` set to `txn_123` after that.

I'll close this issue as this isn't a bug with the SDK itself and more an integration support question. If you have a follow up question, you can talk to my team on Discord for help: https://stripe.com/go/developer-chat

**Comment by leodip** [comment]
@remi-stripe Ok, I see. Thanks for this explanation. I'll take a look at the info provided.
