### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by SoftCircuits** [stripe/stripe-dotnet#3005]
### Describe the bug

The description for this repository says "_The official Stripe .NET library, supporting .NET Standard 2.0+, .NET Core 2.0+, and .NET Framework 4.6.1+._" But when I look at Strip.NET on NuGet, the description says "_Stripe.net is a sync/async .NET 4.6.1+ client, and a portable class library for the Stripe API._" So which is it? Which is the library for .NET Core?

### To Reproduce

N/A

### Expected behavior

N/A

### OS

Windows 11

### .NET version

.NET Core 8

### Library version

v46.2.0

### API version

N/A

**Comment by jar-stripe** [comment]
Hi @SoftCircuits , thanks for bringing this to our attention!  I think this is a documentation issue.  The NuGet package located  here: https://www.nuget.org/packages/Stripe.net does support .NET/.NET Core, .NET Standard, and .NET Framework; you can checkout https://www.nuget.org/packages/Stripe.net#supportedframeworks-body-tab for their display of the frameworks we support.

I'll log an issue to make sure our description is updated correctly.

Does that resolve your issue here?

**Comment by SoftCircuits** [comment]
@jar-stripe Yes, thanks.

**Comment by jar-stripe** [comment]
Great!  I'll close this issue for now, but let us know if we can be of any further help.
