### ISSUE TITLE
Duplicate jsonproperty "external_account" in StripeAccountSharedOptions

### ISSUE THREAD

**Issue by phl3x0r** [stripe/stripe-dotnet#648]
jsonproperties "should" be unique to allow deserialization to StripeAccountCreateOptions and StripeAccountUpdateOptions which both inherit from StripeAccountSharedOptions.

Error when deserialization:
{"A member with the name 'external_account' already exists on 'Stripe.StripeAccountCreateOptions'. Use the JsonPropertyAttribute to specify another name."}

**Comment by jaymedavis** [comment]
is this feature needed anymore? the way it is currently setup makes it easy to provide a card or a bank accounts for users. I don't think I want to change this to a single source property. with the new `StripeResponse`, you can retrieve the full serialized value of what was received from Stripe.

**Comment by banderberg** [comment]
The properties with duplicate JsonProperty values are causing our Swagger UI to fail.  Not sure if you're familiar with that product but it doesn't like this.  I've posted to their GitHub forum but if you happen to know a resolution please let me know, thanks.

**Comment by jaymedavis** [comment]
yes, i've used swagger. can you link to your post?

I'm not sure the best way to handle this. At one time, I had source as one property where you could pass a token or credentials (StripeSourceOptions). This was causing a headache for stripe because users kept trying to use both. I'm open for ideas to help mitigate this.

**Comment by banderberg** [comment]
I had actually posted to the wrong github forum but have corrected that, here is my post:

https://github.com/domaindrivendev/Swashbuckle/issues/979

**Comment by jaymedavis** [comment]
I guess there isn't anything that can be done with swashbuckle. The fix in Stripe.net could be having a nested object for everything that has two properties - for instance - Source object > Token OR Details. If you could compile me a list of all the places swashbuckle fails, I can see what our options might be. However, if they are major changes that will make the library harder to use, I will probably lean towards not fixing this. I hope that is not the case. Per the swashbuckle maintainers request, I would just close that issue and we'll see if we can get it working on this side. :thumbs-up:

**Comment by AFallad** [comment]
Hello!
Are there plans to work  on this? The underlying issue is that the Newtonsoft.Json library checks for dupes in 
[here](https://github.com/JamesNK/Newtonsoft.Json/blob/e1dfefe00b77b82e844771c1ad3d66fa94f8c057/Src/Newtonsoft.Json/Serialization/JsonPropertyCollection.cs#L73) and I couldnt find a way to override this. 

The current workaround I'm using is ignoring the JsonProperty attribute, but it's not ideal.
``` cs
public class StripeContractResolver : DefaultContractResolver
{
    protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
    {
        var property = base.CreateProperty(member, memberSerialization);
        property.PropertyName = property.UnderlyingName;
        return property;
    }
}
```

**Comment by ob-stripe** [comment]
The root cause of this issue is that the library uses Newtonsoft.Json's attributes on request parameter classes, but requests are encoded using `application/x-www-form-urlencoded` encoding, not JSON.

I don't think we will fix this issue, at least not in a way that will enable JSON serialization of request parameter classes. What we should probably do is stop using Newtonsoft.Json's `JsonProperty` attribute and define our own `FormProperty` attribute, and look for those in our encoding logic.

**Comment by ob-stripe** [comment]
Contrary to what I said in my previous comment, we've made changes to the library to allow serializing options classes. As of version 27.0.0, you should now be able to serialize any options class instance to JSON.
