### ISSUE TITLE
Need to support getting a total count from the StripeInvoiceService.

### ISSUE THREAD

**Issue by niemyjski** [stripe/stripe-dotnet#80]
Thanks for your great wrapper! I noticed that there is no way to get the total record count of how many stripe invoices there are. This makes paging harder.. if you don't have a total count. Can this be added to the api as maybe an out parameter

var invoiceService = new StripeInvoiceService();
var invoices = invoiceService.List(pageSize, skip);

**Comment by hmmdeif** [comment]
I realise that this issue is old, however I have just come across it and I think the API has been updated since the last time this has been looked at:

`You can optionally request that the response include the total count of all invoice items that match your filters. To do so, specify include[]=total_count in your request.`

This is the same for all list queries, so I guess they'd all need updating?
