### ISSUE TITLE
Received unknown parameter: customer

### ISSUE THREAD

**Issue by SOflapierre** [stripe/stripe-dotnet#947]
Hi,

When I'm trying to do an update subscription I get this error
Received unknown parameter: customer

any Idea ?

`            Public Shared Sub Update(ByVal SubscriptionID As String, ByVal customerId As String, ByVal StripePlanID As String, ByVal DefaultSourceID As String)
                Dim StripeSubscriptionService = New StripeSubscriptionService()
                StripeSubscriptionService.ApiKey = APISecrectKey_Test
                Dim updateoption As New Stripe.StripeSubscriptionUpdateOptions
                updateoption.CustomerId = customerId
                updateoption.PlanId = StripePlanID
                updateoption.Source = DefaultSourceID
                updateoption.ProrationDate = Now
                updateoption.Prorate = True
                updateoption.Quantity = 1

                Dim StripeSubscription As StripeSubscription = StripeSubscriptionService.Update(SubscriptionID, updateoption) '; // optional StripeSubscriptionCreateOptions
            End Sub`

**Comment by remi-stripe** [comment]
@SOflapierre The issue is that `CustomerId` should not be passed when updating a subscription. This is a parameter that is expected when you create a subscription and not on update. Simply remove this from your code and the update should work.

@jaymedavis You likely want to remove `CustomerId` from [SubscriptionSharedOptions](https://github.com/jaymedavis/stripe.net/blob/32c582b1747f38e79b6e97a0a4d3e2f8fc6e29b6/src/Stripe.net/Services/Subscriptions/SubscriptionSharedOptions.cs#L24) and instead move it to [StripeSubscriptionCreateOptions](https://github.com/jaymedavis/stripe.net/blob/83d280441218c45833682f05fdfd0445ca7e261d/src/Stripe.net/Services/Subscriptions/StripeSubscriptionCreateOptions.cs#L8)

**Comment by SOflapierre** [comment]
that was easy...
didn't think about that... 
didn't think about the fact that adding too mush information can cause me a problem :)

thanks for your help...

**Comment by jaymedavis** [comment]
Leaving this open to fix :)

**Comment by tienvv1991** [comment]
nice it's so useful for me
