### ISSUE TITLE
Issue with customer Sources not being deserialized correctly

### ISSUE THREAD

**Issue by mkieloch352** [stripe/stripe-dotnet#949]
I upgraded to the newest release (10.1) and I noticed something strange. I make a call using the StripeCustomerService to get the customer on my server and return the response back to my Android app. Now when I return the JSON via WebApi it gets serialized correctly, but when I try to deserialize it in my Android app, the Card object on each of one the sources is null. 

![image](https://user-images.githubusercontent.com/1508301/27621231-65ae1180-5b9d-11e7-84af-7f283f390b06.png)

I am using JSON.net 9.0.1 on by the server and in the Android app. Any ideas why this could be happeneing?

**Comment by titchchris** [comment]
I'm experiencing a similar problem, but within the StripeCharge object. 

Looks to me like the Source property on StripeCharge (and StripeCustomer in your case) should be of type StripeSource, but is instead type Source.

**Comment by yoat** [comment]
I'm experiencing the same problem as mkieloch352, with the Card not deserializing from the JSON using the classes and converters (tested in versions 10.0.0, 10.0.3, and 10.0.4).  I'm using Newtonsoft's JsonConvert package 10.latest.  

Raw JSON snippet:
`"sources":{  
    "object":"list",
    "data":[  
      {  
        "Type":0,
        "Deleted":null,
        "Card":{  
          "object":"card",
          "brand":"Visa",
          "exp_month":12,
          "exp_year":2022,
          "funding":"credit",
          "last4":"4242",
          ...
          "id":"card_1AodGrKuE3bdQtIeiV7asxtc",
          ...
`

De/reserialized response (which matches in memory POCO):
`Sources": {
  "Object":"list",
  "Data":[{
    "Type":0, 
    "Deleted":null,
    "Card":null,
     "BankAccount":null,
      "Id":"card_1AodGrKuE3bdQtIeiV7asxtc",
      "StripeResponse":null
}],`

**Comment by anelder-stripe** [comment]
@mkieloch352 - Rather than attempting to deserialize from the POCO, you should get the raw JSON from the `StripeResponse` attribute described here:

https://github.com/stripe/stripe-dotnet#responses

That object will be deserializable by other libraries.  The issue here is that there is no logic-less mapping from the POCO to the JSON objects.  This is due to some ambiguities around what could be in attributes of an object (eg. Source<Card> vs. Source<BitCoin> objects).

If that doesn't work for you, please reach out to us @ https://support.stripe.com/email and we can work with you a bit more.

**Comment by anelder-stripe** [comment]
I've closed this issue in favor of Issue #991.
