### ISSUE TITLE
Bitcoin

### ISSUE THREAD

**Issue by tiagoromano** [stripe/stripe-dotnet#958]
Dear, is there any way to make available a simple way to make a payment with bitcoin, in the same way that you make available to credit card?

On the card I create the token by passing the var myToken = new StripeTokenCreateOptions
             {
                 Card = new StripeCreditCardOptions
                 {
                     Cvc = creditCard.Cvc,
                     ExpirationMonth = creditCard.ExMonth,
                     ExpirationYear = creditCard.ExYear,
                     Name = creditCard.Name,
                     Number = creditCard.Number
                 }
             };
And I move to the StripeTokenService and I get the Id
I did not find a Bitcoin option, like the Card

After creating the token, create the StripeChargeService as the card? Keeping the work the same?

**Comment by remi-stripe** [comment]
@tiagoromano First off, I wanted to mention that at the moment you are sending card details through the API directly. This means that you get the card numbers on your server which has some serious PCI compliance  [implications](https://stripe.com/docs/security#validating-pci-compliance). I would strongly advise you to modify your integration so that you always tokenize the card details first client-side.

You'd need to use [Elements](https://stripe.com/docs/elements) or [Stripe Checkout](https://stripe.com/docs/checkout) client-side to send the card details to Stripe directly and get a unique card token (tok_XXX) that you'd then send safely to your server to create the customer. This along with using an SSL certificate on your payment pages and never sending card details to your server makes you fall under SAQ-A and make sure you're PCI compliant and we take the reporting burden away from you.

Once you fix this, you should follow the same logic for Bitcoin sources. You would create the Source client-side and then you can charge it server-side with Stripe.net. You can read more about this in our documentation [here](https://stripe.com/docs/sources/bitcoin)

**Comment by tiagoromano** [comment]
Okay, but I'm creating an API, there's no interaction with HTML, I have no way to add .js files. It's a method that receives payment under SSL, the data on the card is not stored, simply refer to Stripe.

I wanted to keep this interaction simple, I would like to see just one example of how to make a payment using bitcoin, with the stripe.net library, because I have not really been able to find any examples yet.

For you to have an idea, look how simple the payment part of the card, I have a service that takes care of the interaction with Stripe.net
 public class StripeReponse
    {
        public string Token { get; set; }
        public string TokenCharge { get; set; }
    }

    public class StripeService
    {
        public StripeReponse AddPayment(CreditCardDTO creditCard, decimal amount, string description)
        {
            var token = CreateToken(creditCard);
            var tokenCharge = ProcessPayment(Convert.ToInt32(amount * 100), description, token);
            return new StripeReponse
            {
                Token = token,
                TokenCharge = tokenCharge
            };
        }

        private string CreateToken(CreditCardDTO creditCard)
        {           
            var myToken = new StripeTokenCreateOptions
            {
                Card = new StripeCreditCardOptions
                {
                    Cvc = creditCard.Cvc,
                    ExpirationMonth = creditCard.ExMonth,
                    ExpirationYear = creditCard.ExYear,
                    Name = creditCard.Name,
                    Number = creditCard.Number
                }
            };          

            var tokenService = new StripeTokenService(System.Configuration.ConfigurationManager.AppSettings["StripePublicKey"]);
            var stripeToken = tokenService.Create(myToken);
            
            return stripeToken.Id;
        }

        private string ProcessPayment(int amount, string description, string token)
        {            
            var myCharge = new StripeChargeCreateOptions
            {
                // convert the amount of £12.50 to pennies i.e. 1250
                Amount = amount,
                Description = description,
                SourceTokenOrExistingSourceId = token,
                Currency = "usd",                
            };

            var chargeService = new StripeChargeService(System.Configuration.ConfigurationManager.AppSettings["StripeSecretKey"]);
            var stripeCharge = chargeService.Create(myCharge);

            if (!string.IsNullOrEmpty(stripeCharge.FailureMessage))
                throw new Exception(stripeCharge.FailureMessage);

            return stripeCharge.Id;

        }
    }

**Can you provide an example of how to make a payment using bitcoim please? (Using the stripe.net library) Or indicate somewhere that has an example?** Thanks!

**Comment by remi-stripe** [comment]
@tiagoromano  even if you do not store the card details, they go through your server. This means that you fall under SAQ D for PCI compliance. This is unlikely to be what you want (though I have no details on your business).

As for creating a bitcoin source server-side you can always refer to the test suite of the library. For example [this test](https://github.com/stripe/stripe-dotnet/blob/d9c064ad52b71396964ef5e5713b42cddb2be1ae/src/Stripe.Tests.XUnit/sources/creating_and_updating_bitcoin_source.cs#L12) is creating and updating a bitcoin source.
