### ISSUE TITLE
IEnumerable conversion error when listing Charges

### ISSUE THREAD

**Issue by RDVasavada** [stripe/stripe-dotnet#959]
Stripe.Net version: 1.10.0

I am unable to run this code:
```    
StripeChargeService ChargeService = new StripeChargeService();
StripeChargeListOptions options = new StripeChargeListOptions();
options.CustomerId = model.StripeCustomerID;
IEnumerable<StripeCharge> Charges = ChargeService.List(options);
```
Due to an error I receive. The message is "Cannot implicitly convert type 'Stripe.StripeList<Stripe.StripeCharge>' to 'System.Collections.Generic.IEnumerable<Stripe.StripeCharge>'. An explicit conversion exists (are you missing a cast?"

If I try explicitly casting to IEnumerable, it throws a runtime error. 

I do not have this problem with listing any other Stripe items, such as customers or invoices.

**Comment by anelder-stripe** [comment]
It looks like this is peppered throughout the code `IEnumerable` and `StripeList` to be used interchangeably at times in the definitions.  We should probably fix this and pick one.

**Comment by anelder-stripe** [comment]
I don't think we should be using IEnumerable in 99% of cases where pagination is a possibility, because you lose the `has_more`-attribute, I think.  (Though I could be wrong.)

Affected `List()`-methods should have their return types modified to `StripeList<T>` and their mapper call modified like this:

`Mapper<StripeList<T>>.MapCollectionFromJson()` -> `Mapper<StripeList<T>>.MapFromJson()`

This is after just a quick overview.  @fred-stripe + @remi-stripe + @jaymedavis -- do any of you have a second to confirm what I'm thinking here?  Maybe I am missing something in my understanding?

**Comment by jaymedavis** [comment]
> I don't think we should be using IEnumerable in 99% of cases where pagination is a possibility, because you lose the has_more-attribute, I think. (Though I could be wrong.)

You are right. 😁 

The old IEnumerable/List stuff was pre-pagination days and hasn't been updated. You could run through most services and update them to `StripeList<T>` as you suggested. 

The release notes could let all upgrading users know to change their code from  
```service.List();``` to ```service.List().Data```, to get the `List<T>` back.

@RDVasavada - try ```ChargeService.List(options).Data```

**Comment by anelder-stripe** [comment]
@jaymedavis - My instinct on the fix here would be to `StripeList` to extend both `List` and `StripeEntity` through some kind of intelligent interface design.  The intention being allowing `StripeList<T>` to be cast to `IEnumerable<T>` so that it doesn't break any existing integrations, but also allowing them to grab that same information from the top-level of the object.

ie. supporting looping over the top-level object, looping over the `data` attribute on the top-level object, and access to all of the top-level attributes for pagination.

That sounds feasible right?  Feel free to ignore, more just writing out my thoughts!  Haha.

**Comment by jaymedavis** [comment]
@anelder-stripe clever idea! I think this might work...

Seems like you could make StripeList<T> implement IEnumerable, then just have the `GetEnumerator()`  function return the Data property. I might be missing something... but seems feasible.
