### ISSUE TITLE
[Feature] Add Ips/Ips-Webhooks to Library

### ISSUE THREAD

**Issue by ry8806** [stripe/stripe-dotnet#963]
Feature Request:

Add the ability to get the Ip Addresses and Ip Addresses for webhooks:

Found here (towards the bottom of the page, above questions):
https://stripe.com/docs/ips

Mainly i'm bothered about the webhook ip addresses and verifying on a webhook that they match the list from stripe

I think this would be nice if it was baked in to the Library, would you take a pull-request for this feature?

**Comment by anelder-stripe** [comment]
Hey @ry8806!  I've got similar feelings, but I don't know that the solution is to bake those IP Addresses into the bindings.

These two components, Stripe IP Ranges and API Libraries, seem very disconnected and should remain modular and distinct in my opinion.  I think an alternative approach of extending the API to serve those IP Ranges when a request to a particular endpoint is made (probably on a different subdomain or API than the one used for processing transactions) might be a bit more maintainable.

If you think that's a good idea, I'd be happy to pitch it to the Engineering team internally.  I don't think we'll be able to extend support for baking them in here though.

**Comment by ry8806** [comment]
Sorry, I think I've confused things with my incorrect usage of the term "baked-in", it's been a long day.

What I meant was it would be nice to expose a method in the library which hits these endpoints and returns the list of IP addresses.

Maybe a static method (as it doesn't require any auth on a request or any inputs)

Thanks for your quick response

**Comment by anelder-stripe** [comment]
Hey @ry8806.  Got it.  Yeah, that makes sense.  It's something you'd want to file as a feature request through https://support.stripe.com/email though, as it's agnostic of the `stripe-dotnet` language library itself.  This is something that would need to be built into all of our libraries, rather than just this one.  It's also something that we'd need to build into our infrastructure.  Would you like to file the feature request or would you like me to file it on your behalf?

**Comment by jaymedavis** [comment]
Secure webhooks are part of the library, if that helps. You wouldn't be able to match the IP, but you can verify the webhook came from Stripe this way.
