### ISSUE TITLE
Divide the XUnit Namespaces into objects

### ISSUE THREAD

**Issue by anelder-stripe** [stripe/stripe-dotnet#976]
Right now every test is in the same namespace.  I'm not sure if this is deliberate or not.  I think it might be nice to divide the namespaces by objects, so then testing a single object becomes a bit easier.

@jaymedavis - Is this a deliberate design decision?  Would doing this be dumb?

**Comment by jaymedavis** [comment]
Yes, it's deliberate.  I used a visual test runner so separating the namespace didn't matter. A lot of items in the library itself share the same namespace as well. The reason is it gave me the freedom to move things around as I wanted without having to refactor anything in the code. The usual .net recommendation is to make the namespace match the folder path, so there's nothing wrong with doing this - it's more conventional.

**Comment by ob-stripe** [comment]
We've rewritten the entire test suite in #1236. The folder tree and namespaces in the `StripeTests` project match those in the `Stripe.net` project. Most resources are at the namespace root, but newer resources (for Issuing, Terminal, etc.) have their own sub-namespaces.
