### ISSUE TITLE
Unable to fetch Payouts by date

### ISSUE THREAD

**Issue by trufun202** [stripe/stripe-dotnet#982]
Hi there,

I am unable to fetch Payouts for a date that is too far in the past.  For example, in the Stripe dashboard, I can see that I have Payouts back from 1/4/2017; however, using Stripe.net I'll increment dates starting 1/1/2017 and it isn't returning a Payout until 4/3/2017.  I've tried fetching the results in two ways:

First approach:
```
StripePayoutListOptions payoutOptions = new StripePayoutListOptions();
payoutOptions.Status = "paid";

var payouts = _PayoutService.List(payoutOptions).ToList().Where(p => p.ArrivalDate == new DateTime(TransferDate.Year, TransferDate.Month, TransferDate.Day));
```

Second approach:
```
StripePayoutListOptions payoutOptions = new StripePayoutListOptions();
payoutOptions.Status = "paid";
payoutOptions.ArrivalDate = new DateTime(TransferDate.Year, TransferDate.Month, TransferDate.Day);

var payouts = _PayoutService.List(payoutOptions).ToList();
```

The second approach does not return any data, regardless of the ArrivalDate.

What is the best way to fetch a Paid Payout by Arrival Date?

Thank you,
-Chris B.

**Comment by fred-stripe** [comment]
Hi @trufun202, sorry for the long delay in this reply. We're working to catch up on these issues and should reply much sooner from here on out.

 The reason you're not retrieving any payouts is because the Stripe API is trying to find an exact match for the date you specified, down to the second. However, payouts aren't created strictly at midnight, so you must instead query a 24 hour window to catch all payouts that happened during a certain calendar day. Here's an example of this:

```csharp

StripePayoutListOptions payoutOptions = new StripePayoutListOptions();

var date =   new DateTime(TransferDate.Year, TransferDate.Month, TransferDate.Day)
payoutOptions.Status = "paid";
payoutOptions.ArrivalDate = new StripeDateFilter({
  GreaterThan = date,
  LessThan = date.AddDays(1),
});

var payouts = _PayoutService.List(payoutOptions).ToList();

```

That will return the expected results. Hope that clears things up!
